### ISSUE TITLE
Change in morning schedule for meeting partner

### ISSUE THREAD

**Issue by rna** [microverseinc/microverse-issue-tracker#104]
There is a change in the morning schedule from the august batch onwards. Refer to this [link](https://microverse.zendesk.com/hc/en-us/articles/360037383833-15-10-2019-Algorithms-Data-Structure-overhaul-stage-1-challenges-start-after-Ruby) for more info.

With reference to the changes, we suppose to meet coding partner after half an hour meeting with the stand-up team. But the join option is not enabling until 5mins before the actual schedule (ie. 8:55 am UTC-6).

**Comment by Keqi** [comment]
Hi @rna,

Thanks for noticing it. We're aware of the changes in schedule and we'll soon adjust them in the Dashboard :) I'll keep you posted.

**Comment by FreeLydia** [comment]
@Keqi - I thought we implemented a hot fix so both buttons are present when it hits 8:30am?

**Comment by Keqi** [comment]
@FreeLydia Yes but the implementation did not cover some cases. I am looking into it :)

**Comment by Keqi** [comment]
Hi @rna, @FreeLydia 

This should be fixed by now.
