### ISSUE TITLE
Marked as absent

### ISSUE THREAD

**Issue by mkezmkez** [microverseinc/microverse-issue-tracker#106]
Hello, 

My name is Luis Puente puente.luism@gmail.com, I'm submitting this issue because I noticed I was marked as absent last friday 2019-10-25 when I've never actually missed a meeting. 

Hope you can help me get this fixed. Thank you.

Luis

**Comment by Keqi** [comment]
Hello @mkezmkez,

I'll merge your issue with your partner report because you both were marked as absent on the same time: https://github.com/microverseinc/microverse-issue-tracker/issues/107

**Comment by mkezmkez** [comment]
I still have this absence showing in my dashboard :(
