### ISSUE TITLE
Randomly being marked absent only for the daily standup

### ISSUE THREAD

**Issue by rsundar** [microverseinc/microverse-issue-tracker#108]
I have been marked absent on the daily standup meeting on the 25th and 28th of October when I was in fact present for the same, this can be verified by the members of my standup committee.

Kindly advise,

Rohan

**Comment by Keqi** [comment]
Hi Rohan,

It's very interesting. Our system does not see you in these meetings. According to the logs, only Abdusaid Abdurasulov and Emmanuel Kamala were present in these meetings.

**Comment by Keqi** [comment]
Closing as there is no response for 7 days.
