### ISSUE TITLE
my dashboard week display not in sync

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#109]
My current dashboard displays rather my last week's status for this week
''October 28 - November 03''
https://dashboard.microverse.org/dashboard#dashboard-calendar

**Comment by FreeLydia** [comment]
Hi @ngodi - I see your current schedule showing for Nov 4-10. Can you check again?
<img width="918" alt="Screen Shot 2019-11-04 at 9 55 14 AM" src="https://user-images.githubusercontent.com/47569337/68108826-3d40c200-fee9-11e9-82dd-b26d4ddd2b17.png">

**Comment by ngodi** [comment]
Oh yeah!,  it's fine now, thanks
