### ISSUE TITLE
Can't submit retrospective for last week

### ISSUE THREAD

**Issue by mosesogwo** [microverseinc/microverse-issue-tracker#111]
I get the error message "Retrospective was already submitted for this week." when I attempt to submit retrospective for the week that ended on 1st Nov. 2019.

**Comment by Keqi** [comment]
Hi @mosesogwo,

This error means that you have already selected `1st Nov. 2019` as a `Retrospective Date` field in one of your submissions. Is this correct?

If you're late with your submission, you always have to select `Retrospective Date` pointing to the day when a submission was supposed to be added. For example: If you filled out your Retro form on November 4th, 2019 (Monday), you should still select November 1st, 2019 as `Retrospective Date`.

Let me know if this is clear for you :)

**Comment by Keqi** [comment]
Closing as there is no confirmation or response for 7 days.
