### ISSUE TITLE
DST. 

### ISSUE THREAD

**Issue by paulgureghian** [microverseinc/microverse-issue-tracker#112]
I set my clock back an hour for DST, and when I joined the stand up this morning, I was am hour late. I should have been on time or if anything else, an hour early, not an hour late.

**Comment by Keqi** [comment]
Hi @paulgureghian,

Is this still a problem for you?

**Comment by paulgureghian** [comment]
I am getting up an hour earlier now.

**Comment by Keqi** [comment]
Hi @paulgureghian,

I don't think I fully understand your problem. Do you have to get up earlier than usual to work with your team?

**Comment by paulgureghian** [comment]
I was getting up at 7 am, now I have to get up at 6 am. I didn't know that and I was marked absent once or twice before I made the adjustment. I would like those absences reversed.

**Comment by Keqi** [comment]
Hi @paulgureghian,

We won't be able to mark these absences manually but they won't be counted against your progress so there is nothing to worry about :)
