### ISSUE TITLE
Broken Link in Pathwright

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#113]
The link in the SQL project sends us to a deactivated form (https://airtable.com/shrpRM04DRuN7jleZ) when it should be sending us to the dashboard.

I would suggest adding the completion form option to that project since it makes you request a code review but there's nothing to review.

**Comment by gootyfer** [comment]
Thanks for reaching out @majovainilla ! I've already updated the link in Pathwright. And it's fixed!! :)

![eyes](https://user-images.githubusercontent.com/759396/68466628-164dfd00-0215-11ea-84ee-3dc952b370a4.gif)
