### ISSUE TITLE
I got incorrect recorded absent from zoom system. 

### ISSUE THREAD

**Issue by kelvin8773** [microverseinc/microverse-issue-tracker#114]
I join both morning and standup sections with my register email account in Zoom, but the system catch 2 absents on Nov 6, 2019. 
One thing worth to notice is I joined the morning section a bit late on that day(about 15 minutes late) and stay till the end. 
And join the standup section on time.

feel free to contact me if you want more detail about this incident, thanks again for your help!

Kelvin
Slack: @Kelvin

**Comment by Keqi** [comment]
Hi @kelvin8773,

Our absences tracker does not synchronize the data immediately. It's a delayed process. Sometimes, you may see yourself absent in the current day but it will be gone after several hours.

According to my logs, your absences are gone. Am I right?

**Comment by kelvin8773** [comment]
@keqi, yes, you are right, they are gone in next day, but I thought it is because someone manually remove it. but anyway, it is small bug, I just report here hope it help you guys make the system better.
