### ISSUE TITLE
Incorrect Absence Recorded

### ISSUE THREAD

**Issue by Qoosim** [microverseinc/microverse-issue-tracker#116]
I checked attendance and absences on my dashboard and to my surprise, I found four solid absences on my profile which is totally not true. I never missed any stand-up meeting ever since I started my program in Microverse since August 12. Please help to look into this

**Comment by Keqi** [comment]
Hi @Qoosim,

Can you please send me your email address so I can verify your absences log?

**Comment by Qoosim** [comment]
ayinde.abdulghaniyy@gmail.com

**Comment by Keqi** [comment]
Hi @Qoosim,

It seems like our system log can not find you in these meetings. Are you sure you joined the correct room or team these days?

**Comment by Qoosim** [comment]
Yes I did with no doubt.

**Comment by Keqi** [comment]
I can see your teammates present on these meetings and you were not. Do you think you could have trouble with connection? Is there a possibility your connection was dropped or not solid enough? Sometimes Zoom wouldn't add you as a participant if this was a case.

**Comment by Qoosim** [comment]
I cannot decipher what really transpired as at the time. I was in the
meeting throughout.

**Comment by Keqi** [comment]
I can not decipher your absences either. Let's ignore them for now and see if more absences appear on your dashboard in the future.

**Comment by Qoosim** [comment]
Alright
