### ISSUE TITLE
Join Call buttons showing for both Morning session and collaborative learning.

### ISSUE THREAD

**Issue by Chincoya** [microverseinc/microverse-issue-tracker#118]
Half an hour into the morning session I went into the dashboard and found both buttons enabled. 

![Screenshot_2019-11-08 Dashboard](https://user-images.githubusercontent.com/21246606/68484414-d54ced00-0202-11ea-9cf6-316c6f355ae7.png)

**Comment by Keqi** [comment]
This is intentional behavior as we're in the process of altering our daily schedule. @nidalaa can you point to the article or announcement explaining this change?

**Comment by Keqi** [comment]
Hi @Chincoya,

Please reach out to @nidalaa directly on Slack if you want to read the announcement. It's not a bug, we allow students to smoothly jump between calls in the morning.
