### ISSUE TITLE
Submission Error on repl.it challenge 7.11

### ISSUE THREAD

**Issue by KerronKing** [microverseinc/microverse-issue-tracker#119]
Good Day,

In trying to make a submission on repl.it for challenge 7.11 (Quick Sort Advanced), an error arose where the test cases show as "passed" but the window still says "failed". Please assist.

**Comment by Keqi** [comment]
Hi @KerronKing,

It's interesting. @nidalaa @gootyfer can you see what is happening?

**Comment by gootyfer** [comment]
Hi @KerronKing,

Sorry for the long wait. Will you please share a screenshot of the problem you had? Will you elaborate more about what happened? I mean, you run the tests on your solution of 7.11 challenge and it got passed but the error arose when you submitted? Any other error message apart from "failed"? Thanks!

**Comment by KerronKing** [comment]
![Screenshot 2019-11-18 at 11 01 18 AM](https://user-images.githubusercontent.com/49284298/69063430-db0cb480-09f2-11ea-9976-0549f43b398f.png)

**Comment by KerronKing** [comment]
It isn't giving me any error messages beyond what can be seen in the screenshot above. When clicking "What's wrong?", it simply says "Failed tests".

**Comment by gootyfer** [comment]
Hi @KerronKing, 

I was able to reproduce your error. I contacted the repl.it team to fin out how to fix the error.

Thanks the detailed info. I'll make you know about my progress.
Best regards,
Israel

**Comment by gootyfer** [comment]
Hi @KerronKing ,

I was finally able to fix the issue by updating our test cases. Please, try it and check if it works.

Best,
Israel
