### ISSUE TITLE
Milestone set to "Changes Required" even though approval was given

### ISSUE THREAD

**Issue by KerronKing** [microverseinc/microverse-issue-tracker#12]
The status of Milestone 3 for my OOP project in Ruby says "Changes Required" even though it was approved for submission. My partner's dashboard status changed and he was able to submit. However, mine hasn't yet updated.

**Comment by nidalaa** [comment]
Hi @KerronKing !

Thank you for your report - we are working on that!

**Comment by nidalaa** [comment]
Hi @KerronKing the issue has been fixed! You can see correct status now and submit your project completion form :)

Thanks!

**Comment by rmauritsson** [comment]
Hello @nidalaa 
I have the same issue. What should i do?

**Comment by nidalaa** [comment]
@rmauritsson could you open a new separate issue and provide details there (name of the project, name of your coding partner)?
