### ISSUE TITLE
Absence not correct

### ISSUE THREAD

**Issue by Kyrule** [microverseinc/microverse-issue-tracker#120]
Greetings Sir/Mdm, 

I realized that there are detected absences on my dashboard for the
29th october 2019. 

May I say that for the record that this is not true. 

I was present for the stand up meeting and I filled in the form. 

Let me know if you have further questions. 

Regards, 

                                
Khairul

**Comment by Keqi** [comment]
Hi @Kyrule,

Can you please send me your email address so I can debug your issue?

**Comment by Kyrule** [comment]
> Hi @Kyrule,
> 
> Can you please send me your email address so I can debug your issue?

khairulkulma at gmail dot com

**Comment by Keqi** [comment]
Our system couldn't find you at this particular meeting. Are you sure you joined the correct meeting room and didn't have connection issues?

**Comment by Kyrule** [comment]
> Our system couldn't find you at this particular meeting. Are you sure you joined the correct meeting room and didn't have connection issues?

hi @Keqi 
Yes. I am very sure that I joined the meeting via microverse zoom. 29th October and the 8th Nov, present for both.

**Comment by Keqi** [comment]
Is there any chance you had trouble with your connection or dropped from the meeting several times? In such a case, Zoom might not recognize you as a participant.

**Comment by Keqi** [comment]
No response for 8 days. Closing.
