### ISSUE TITLE
This is the second time I have been Incorrectly marked absent

### ISSUE THREAD

**Issue by collinsugwu** [microverseinc/microverse-issue-tracker#123]
I was marked absent on 8-11, while I attended the call both morning and night.
 I would appreciate if it is rectified.

**Comment by Keqi** [comment]
Hi @collinsugwu,

It seems like your entire team met around 12 pm on Friday and stayed in the meeting for 5 hours. This isn't according to the Daily Stand-Up schedule. That's why you were marked as absent.

**Comment by collinsugwu** [comment]
How can we meet for 5hrs

**Comment by collinsugwu** [comment]
> Hi @collinsugwu,
> 
> It seems like your entire team met around 12 pm on Friday and stayed in the meeting for 5 hours. This isn't according to the Daily Stand-Up schedule. That's why you were marked as absent.

If that be the case, I think we shouldn't be penalised for being absent rather we should be penalized for staying overtime (which is something I'm yet to understand)

**Comment by Keqi** [comment]
This issue has been explained and resolved in this [ticket](https://github.com/microverseinc/microverse-issue-tracker/issues/126).
