### ISSUE TITLE
False absent on November 8th

### ISSUE THREAD

**Issue by wickathou** [microverseinc/microverse-issue-tracker#124]
My profile has a wrongly detected absence on the 8th of November, which I see a lot of people got the same issue.

Looking forward for a patch

**Comment by Keqi** [comment]
Hey @wickathou,

It seems like your entire team met around 12 pm on Friday and stayed in the meeting for 5 hours. This isn't according to the Daily Stand-Up schedule. That's why you were marked as absent.

**Comment by Keqi** [comment]
This issue has been explained and resolved in this [ticket](https://github.com/microverseinc/microverse-issue-tracker/issues/126).
