### ISSUE TITLE
marked as absent by accident 

### ISSUE THREAD

**Issue by mohamednaser** [microverseinc/microverse-issue-tracker#125]
all my time is marked as an absence in 2019-11-09 and we are not be absent  also other days I just forgot to submit the morning standup form and in the next day I submitted it 

![issue with absent](https://user-images.githubusercontent.com/6272923/68628616-c5c2f200-04e9-11ea-823e-5d0addeae9b3.png)

**Comment by Keqi** [comment]
Hey @mohamednaser,

It seems like your entire team met around 12 pm on Friday and stayed in the meeting for 5 hours. This isn't according to the Daily Stand-Up schedule. That's why you were marked as absent.

**Comment by Keqi** [comment]
This issue has been explained and resolved in this [ticket](https://github.com/microverseinc/microverse-issue-tracker/issues/126).
