### ISSUE TITLE
All the partners on my meeting team have the same absent

### ISSUE THREAD

**Issue by Israel-Laguan** [microverseinc/microverse-issue-tracker#126]
Today all of my team (team 52) received the same absent for first meeting on Friday 11-08, and we were there, so we suspect is a mistake. Please check on the issue and if you guys needs any info we are happy to provide it so the problem is solved.

**Comment by Keqi** [comment]
Hi @Israel-Laguan,

It seems like your entire team met around 12 pm on Friday and stayed in the meeting for 5 hours. This isn't according to the Daily Stand-Up schedule. That's why you were marked as absent.

**Comment by Israel-Laguan** [comment]
Hello, and thanks for your response. On that Friday we met at the morning as usual and we did not take 5 hours, maybe there was a problem somewhere? It's almost imposible that scenario you are describing. Do you guys need any kind of proof or a declaration? Please let's solve this weird case, we are really interested in this issue to be solved. Thanks in advance.

**Comment by Keqi** [comment]
Here's what we see in logs for Friday, Nov 8:

First meeting:

start_time: Fri, 08 Nov 2019 13:58:34 UTC +00:00
end_time: Fri, 08 Nov 2019 14:44:29 UTC +00:00
participants:
  - Collins Ugwu
  - Israel Antonio Rosales Laguan
  - Juan Pablo Gil
  - Mohamed Naser
  - Javier hernandez

Second meeting:

start_time: Fri, 08 Nov 2019 18:14:47 UTC +00:00
end_time: Fri, 08 Nov 2019 23:09:00 UTC +00:00
participants:
  - Collins Ugwu
  - Israel Antonio Rosales Laguan
  - Juan Pablo Gil
  - Mohamed Naser
  - Javier hernandez

**Comment by Israel-Laguan** [comment]
Hello and thanks for the detailed response Mr. @Keqi!

To me there are two options:
- [ ] Somehow someone used the meeting link as the normal Pair Programming Meeting link. That explain the duration and the timing.
- [ ] There is an error with the start time.

But I have to say that both options shows the team being present on time for the start of the StandUp Meeting (around 23:00 UTC +00) so **there is no absence in any case**. 

Please take also into consideration that all the names are in the lists for both meetings, showing the commitment of all the team members with assisting to the Standup. We respect the meeting as really valuable and a great chance to grow bondings and learn from others. 

If you guys need any more information from us to have this issue solved we are happy to collaborate and provide anything that you request.

Thanks in advance for your hard work!

**Comment by Keqi** [comment]
Hey @Israel-Laguan,

> Somehow someone used the meeting link as the normal Pair Programming Meeting link. That explain the duration and the timing.

This would explain why your entire team was marked as absent for the Standup. Can you discuss it within your team to use appropriate links for specific meetings. This will prevent situations like this.

> Please take also into consideration that all the names are in the lists for both meetings, showing the commitment of all the team members with assisting to the Standup. We respect the meeting as really valuable and a great chance to grow bondings and learn from others.

You don't have to be worried at all about this particular meeting. It won't count against you. You have explained in detail what has happened. However, we might not be able to fix this record in DB so you'll keep seeing yourself as absent this day.

**Comment by Israel-Laguan** [comment]
Hello and thanks for your fast answer Mr. @Keqi!

> Can you discuss it within your team to use appropriate links for specific meetings. This will prevent situations like this.

Sure thing, we will make this as an exemplum so this issue is not repeated. Thanks for your great help :ok_hand:
