### ISSUE TITLE
I have more than 30 absences showing up today that didn't show up before!!!

### ISSUE THREAD

**Issue by Redvanisation** [microverseinc/microverse-issue-tracker#127]
My **timezone** was changed today and I have more than **30 absences** showing up on my **dashboard** even though **I wasn't absent** at all and these **absences weren't showing yesterday** 😮

**Comment by Keqi** [comment]
Hi @Redvanisation,

Can you tell me what was your previous and what is the new timezone you have? Why did you change a timezone?

**Comment by Redvanisation** [comment]
I was on UTC, then changed to UTC-6 because it was more convenient for me, then I got many incorrect absences, but it is fixed for now as I am back on the UTC timezone again.
