### ISSUE TITLE
Can't join standup sessions via zoom

### ISSUE THREAD

**Issue by uche-inyama** [microverseinc/microverse-issue-tracker#128]
Since yesterday, 11-11-2019, I have not been able to join my standup sessions through zoom calls.
Email: uchenry.iny@gmail.com.

**Comment by Keqi** [comment]
Hi @uche-inyama,

Did you try to sign out of Zoom and sign in again using this link: microverse.zoom.us

**Comment by Keqi** [comment]
This issue was solved by a couple of students by reinstalling the Zoom application. Closing.
