### ISSUE TITLE
Inability to join meetings

### ISSUE THREAD

**Issue by Forison** [microverseinc/microverse-issue-tracker#129]
Hi 
Please, I am unable to join morning and evening standups since Monday. After I click the join but I get redirected to the page below and It gets stuck there without launching the video call. This phenomenon seems to happen to me and one other member fo my team. I would appreciate any help you can give to have this issue resolved as soon as possible
![Screenshot from 2019-11-11 03-09-26](https://user-images.githubusercontent.com/29695661/68654438-eb58f700-04fb-11ea-9213-8d55a974376c.png)

**Comment by Keqi** [comment]
Hi @Forison,

Is this still a problem for you. I saw that some students uninstalled and installed again Zoom application to make it work.

**Comment by Forison** [comment]
Thanks @Keqi ,
It worked after I uninstalled and install zoom...
