### ISSUE TITLE
Incorrect absent issue

### ISSUE THREAD

**Issue by 300ms** [microverseinc/microverse-issue-tracker#13]
Hello,
I have 2 absent issues and sent a ticket with screenshot to support but i've been told that i must submit an issue on github. These absent informations are incorrect and i am adding a screen shoot of it ^^ Can you help me about that please ? 
![screencapture-dashboard-microverse-org-absences-2019-08-30-19_27_21](https://user-images.githubusercontent.com/45623118/64678771-f30c0900-d482-11e9-9f92-b824eb6d83b3.png)

**Comment by Keqi** [comment]
Hi @300ms,

August 12, 2019 was your first day and you probably missed the coding challenge meeting. Please ignore that label, we'll change it soon to not count you as absent if you attended a welcoming call with the Microverse team.

August 19, 2019 - Our system couldn't find you. Are you sure you attended the correct meeting?

Side note: System logs say most of the time it can not recognize your email. Are you following the instructions from the page?

**Comment by 300ms** [comment]
Yes, like you said, 12 august was our first day and we have been told that
we are not going to solve a challenge at that first day. Also in same
welcome meeting, we have been told to join meetings on links on dashboard.
We should use "Join Call" buttons to join calls so we will be able to
tracked by system. And still, i always use those "Join Call" buttons to
join meetings which are at the beginning and the end of the day. And i join
to meetings with my coding partner, i use directives on
Dashboard>Absent&Absences page. I don't know why system does not see me
really. Last 2 days, yesterday morning and before yesterday morning, i
could not join to morning calls but i send a form for my absences. I have
got cold but still i solved challenges and join to calls only except
morning meetings.

Maciej Nowak <notifications@github.com>, 12 Eyl 2019 Per, 07:57 tarihinde
şunu yazdı:

**Comment by 300ms** [comment]
You can ask every detail of everyday and meetings to my mentor, my coding
partner and my team mates ^^ also you can follow my progress day by day on
my dashboard/profile to confirm informations ^^

İlhan Sönmez <ilhansnmz44@gmail.com>, 12 Eyl 2019 Per, 08:12 tarihinde şunu
yazdı:

**Comment by Keqi** [comment]
My recommendation is to sign out of your Zoom account and sign in again. You might have been using your old account.

**Comment by 300ms** [comment]
But my zoom account information page says that it is a microverse account and i am a member of microverse. Here i am adding a screenshot so you can see ^^
![Untitled](https://user-images.githubusercontent.com/45623118/64893570-0f28c980-d680-11e9-9d91-19c2afb70953.png)

**Comment by 300ms** [comment]
I mean i followed directives on absent&absences page to make my zoom account switch to a microverse zoom account. If you think it is the problem, i've already done this ^^

**Comment by 300ms** [comment]
I join to team meetings which are the first and last meetings at the day, stand up team meetings, by using "Join Call" button on dashboard. And i use "microverse.zoom.us" to host/join to meetings with my coding partner.

**Comment by Keqi** [comment]
Interesting. Please, ignore these absences because they won't be counted against you. I see you're following the instructions and you don't have more absences in the Dashboard so all good :)
