### ISSUE TITLE
Incorrect Absences.

### ISSUE THREAD

**Issue by uche-inyama** [microverseinc/microverse-issue-tracker#130]
After the challenge I had yesterday making a zoom call; this morning, I went through my absences, I noticed I was marked absent for yesterday. 
Also, I will take this opportunity to bring this to the teams notice, I forgot to mention it. I have incorrect absences marked, for 1st , 22nd and 23rd of October, I was present in those days, kindly rectify. 

Email: uchenry.iny@gmail.com

**Comment by Keqi** [comment]
Hi @uche-inyama,

It seems like those meetings never took place or you were alone in the meeting room. Is this correct?

**Comment by Keqi** [comment]
No response for 12 days. Closing.
