### ISSUE TITLE
Was unable to submit my retrospective

### ISSUE THREAD

**Issue by lilleonz** [microverseinc/microverse-issue-tracker#132]
Im slow with reporting this. But last friday I was not able to submit my retrospective. kept getting an error that it was already submitted.
![Retrospective Form - dashboard microverse org](https://user-images.githubusercontent.com/13488878/68691392-ac4d9480-0541-11ea-9dab-fc15b34a9a21.png)

**Comment by Keqi** [comment]
Hi @lilleonz,

It seems like you have submitted a Retrospective for this particular week. Very likely, you have forgotten to submit a previous Retrospective and you did it on Monday, selecting `Restrospective Date` as Monday which blocked you from submitting next Retro.

Whenever you submit a retrospective, in the `Retrospective Date` field, please select a day when it was supposed to be sent (last Friday).

**Comment by Keqi** [comment]
No response for 12 days. Closing.
