### ISSUE TITLE
Code Review Request Submission Form shows project is completed when is not the case

### ISSUE THREAD

**Issue by Israel-Laguan** [microverseinc/microverse-issue-tracker#133]
When I try to get a Code Review this pops out when nor my partner nor I had submitted a form to this project.

I am conscious about [this issue](https://github.com/microverseinc/microverse-issue-tracker/issues/61) but seems like we don't have this project on submitted state.

Please help us to request a code review.

**Comment by uzorjchibuzor** [comment]
@Israel-Laguan Thanks for reporting this, we are going to look into this and give an update.
