### ISSUE TITLE
Marked absent

### ISSUE THREAD

**Issue by IBTechRaj** [microverseinc/microverse-issue-tracker#134]
Marked absent on 2019/11/04 for stand up meeting. I could not join as my zoom got stuck and by the time I logged in the meeting was over

**Comment by Keqi** [comment]
Thanks for the explanation. Please, try to make sure your Zoom application works good enough before you join the meeting. Unfortunately, we can not undo this absence because you didn't join.

If this is a single case, it won't be counted against your progress.
