### ISSUE TITLE
Absences.

### ISSUE THREAD

**Issue by Luzaks** [microverseinc/microverse-issue-tracker#135]
Hello, I have two marked absences but I am always attending the stand-up meetings. I am sure they are incorrect. My absences are on 2019-10-09 and on 2019-09-30.

**Comment by Keqi** [comment]
Hi, @Luzaks,

Can you please send me your email address so I can properly debug your case?

**Comment by Luzaks** [comment]
> Hi, @Luzaks,
> 
> Can you please send me your email address so I can properly debug your case?

Sure, it is kanemekanik@gmail.com

**Comment by Keqi** [comment]
Hi @Luzaks,

Sorry for the late response. I can not decipher those two absences because the system sees you as absent. However, I wouldn't be worried because in general, you're doing good and you were not absent since then.

Keep it up!
