### ISSUE TITLE
 Enable submitting code-review related fields empty in project completion form when a project doesn't need/get a review 

### ISSUE THREAD

**Issue by uryelah** [microverseinc/microverse-issue-tracker#136]
**Conditional form validation**

It should not be required to fill the code reviewer input and 'How could the code review have been improved for this project?' text field when the radio input :
'I didn't get a code review' is checked.
 
Since there are projects that do not require reviews, having a conditional for the required fields in the form would create a better user experience

**Comment by Keqi** [comment]
Hi @uryelah,

I totally agree with you. I'll add it to our tasks backlog and see if we can get this done soon. Thanks for the suggestion.

**Comment by uzorjchibuzor** [comment]
@uryelah,

Happy new year, I want to inform you that we are working on this request and it is ongoing. We are going to inform you when it gets to production.

Thank you.

**Comment by Keqi** [comment]
Hi @uryelah,

I am extremely sorry for the delayed message. We're very limited in the Dev team at the moment.

We have tweaked the form and code-review related fields are now hidden if you select the `Solo` project from the drop list.
