### ISSUE TITLE
I keep getting incorrect absence record

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#137]

**Comment by Keqi** [comment]
Hi @ngodi,

I don't see any absences recently in your Dashboard. However, I can see you're requesting a lot of absence requests. In this correct?

**Comment by ngodi** [comment]
Yes, due to illness

**Comment by Keqi** [comment]
Please, clarify this issue with the Student Success team. If you're sick and can not attend the meeting, it's perfectly okay to submit an absence request.
