### ISSUE TITLE
Wrong absences

### ISSUE THREAD

**Issue by stiakov** [microverseinc/microverse-issue-tracker#138]
Hello, can you check my attendance because the first three lines are wrong.
On the 4th of November, I've requested an absent for both meetings, but it stills appears as absent.

![Screenshot 2019-11-14 at 11 34 46 AM](https://user-images.githubusercontent.com/1456388/68876931-37aa5f80-06d3-11ea-9675-becb3168bfe8.png)

**Comment by uzorjchibuzor** [comment]
@stiakov Put my mind at rest, it will not count against you. Happy Learning...

**Comment by uzorjchibuzor** [comment]
@stiakov Are you talking about you `Physiotherapist session` absence request? incase that was the case the request says that you took 14th off. There is no record of absence request on 4th Novemeber made by you. Could you please clarify? If you entered the date in error I can help you make some corrections. Thanks. Uzor.

**Comment by stiakov** [comment]
Hi @uzorjchibuzor! No, I refer to the 2019-11-04. 
If you check the **15th** item in **Requested absences** list and the **5th** item in **Detected Absences** you can see that the request was sent properly and the absence appears yet. Please kindly take a look.

**Comment by uzorjchibuzor** [comment]
@stiakov,

Happy new year and sorry for the late response, I will check the database again to fix this error for you.

Thank you and grateful for your patience.

**Comment by uzorjchibuzor** [comment]
@stiakov The correction have been made and the absence gone from your dashboard. Thanks for your patience.
