### ISSUE TITLE
Abesences

### ISSUE THREAD

**Issue by NaguiHW** [microverseinc/microverse-issue-tracker#139]
A few days ago, I received an email from Greg Barrett, telling me that I had many absences and I was surprised since I have not stopped attending all the meetings.
2 days ago, Greg sent me an email telling me that my morning assistance had been detected, and at night I took a screenshot to prove that I had also attended at night, but the next day in the attendance and absences tab it appeared that I had not attended any of the 2 meetings, and today many of the absences disappeared and 2 remained, which I also attended

**Comment by uzorjchibuzor** [comment]
@NaguiHW Could you kindly send the dates that you were marked absent? Thanks.

**Comment by Keqi** [comment]
No response for 12 days. Closing.
