### ISSUE TITLE
I have an incorrect absence recorded

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#14]
I logged in to my stand up zoom on the 10/09/2019 but was recorded as absent. Hope you find a fix for this.

**Comment by Keqi** [comment]
Hey @ngodi,

Are you following the instructions from the Attendance & Absences page? Our system can't see you on 10/09/2019.

**Comment by ngodi** [comment]
Yes of course, I never had this before

**Comment by Keqi** [comment]
@ngodi Please ignore that absence, it won't be counted against you as the system is still in the beta phase.

For the future reference, please sign out from your Zoom account and sign in to microverse.zoom.us to be counted as present.
