### ISSUE TITLE
Cannot login using chrome browser

### ISSUE THREAD

**Issue by Kyrule** [microverseinc/microverse-issue-tracker#140]
Cannot login using chrome browser. Please see picture below
![image](https://user-images.githubusercontent.com/21096434/68974402-4d448580-07b6-11ea-84e3-f07ef3563062.png)

**Comment by uzorjchibuzor** [comment]
@Kyrule Have you tried using another browser? or a VPN?

**Comment by ClintonEnyinna** [comment]
Go to "chrome://flags/#same-site-by-default-cookies" in your browser. Change the "SameSite by default cookies" to disabled

**Comment by Keqi** [comment]
This issue was resolved yesterday by changing an authentication method on the server-side.
