### ISSUE TITLE
Dashboard schedule layout breaks on screens with width smaller than 990px

### ISSUE THREAD

**Issue by uryelah** [microverseinc/microverse-issue-tracker#141]
![Screenshot_2019-11-18 Dashboard](https://user-images.githubusercontent.com/16193212/69062694-1068d080-09fa-11ea-8724-adb1a7edfcc7.png)

**Comment by uzorjchibuzor** [comment]
@uryelah I can see that you have received feedback on this issue on Slack [here](https://microverse-students.slack.com/archives/GA812K2TC/p1574088600091900)
