### ISSUE TITLE
Attendence issue.

### ISSUE THREAD

**Issue by shshamim63** [microverseinc/microverse-issue-tracker#142]
If we are done with the standup meeting less than 15 minutes, it renders a absence tag on my dashboard.

**Comment by uzorjchibuzor** [comment]
@shshamim63 Can you please send a sample of the dates in these cases? Thanks.

**Comment by shshamim63** [comment]
Sure, 
1. 2019-10-10
2. 2019-10-11
3. 2019-11-07
4. 2019-11-08 (Both, standup and morning session).

**Comment by uzorjchibuzor** [comment]
All of these dates marked you absent for standup meetings except the last one that marked you absent for stand up and morning session right?

**Comment by shshamim63** [comment]
Yes. @uzorjchibuzor

**Comment by uzorjchibuzor** [comment]
How is your internet connection on these dates? This feature is still in better so we are still trying to iron out the wrinkles. That said, I could not see any records for your standup team on 8th November but like I said we are still in beta phase so all this bugs are expected. It will not count against you. Happy coding.
