### ISSUE TITLE
Abscence issue

### ISSUE THREAD

**Issue by kalavhan** [microverseinc/microverse-issue-tracker#143]
it appears as if had been absent in two morning meetings in
-2019-11-18
-2019-11-13
I actually joined through the microverse dashboard clicking the "join call" button
I wish for it to be corrected, thank you!

**Comment by uzorjchibuzor** [comment]
@kalavhan I checked the Zoom and you were obviously present in all the meetings on these dates. That's an interesting situation, It will not count against you. Please be patient with this integration as it is still in beta phase. Happy coding...
