### ISSUE TITLE
The collaborative learning button appearing on my dashboard during the morning meetup call in the same time

### ISSUE THREAD

**Issue by Redvanisation** [microverseinc/microverse-issue-tracker#144]
I have an issue with the meetings buttons, the collaborative learning button is appearing at the same time as the morning session meeting.

<img width="1238" alt="Screen Shot 2019-11-20 at 3 43 33 AM" src="https://user-images.githubusercontent.com/33462180/69222760-1bca1200-0b48-11ea-867d-2a5b6e89c6ba.png">

**Comment by uzorjchibuzor** [comment]
At the time you saw these buttons, was it 9am on the dot? trying to chase down the bug?

**Comment by Redvanisation** [comment]
No, it wasn't 9 AM yet, usually, that button appears after when the other button disappears, but now both are showing at the same time around 8 something AM.

**Comment by Keqi** [comment]
Hi @Redvanisation,

This isn't a bug. This is an intentional change to let you jump smoothly between meetings in the morning. We're introducing some changes to the Daily Schedule and its part of it.

Thanks for the report!
