### ISSUE TITLE
I was not absent please help

### ISSUE THREAD

**Issue by jucora** [microverseinc/microverse-issue-tracker#146]
Hello guys... I hope you are ok

An Absense appears on 2019-11-15, but I was not absent.

Could you please check that, I appreciate your help with this issue.

I'll be waiting for your answer, have a great day!

**Comment by Keqi** [comment]
Hi @jucora,

Is this possible that you're alone in the meeting room? Out system did not record any meeting at this time. This seems like to be your only absence so there is completely nothing to worry about.

**Comment by Keqi** [comment]
Closing as there is no response for 9 days.
