### ISSUE TITLE
Group Discussion Panel Doesnt Close

### ISSUE THREAD

**Issue by jubaan** [microverseinc/microverse-issue-tracker#147]
It opens correctly when you want to see the discussions and their answer but when you want to close it, it doest close all the way... look how the panel stays after closing in the right of the window. Im using firefox browser version 70.0.1 (64-bit)

![httpsmicroverse pathwright comlibrarymicroverse-onboarding86777pathstep55314027discussion218217](https://user-images.githubusercontent.com/25774518/69401911-f4945180-0cbb-11ea-9d5d-3625de2e32cf.png)

**Comment by Keqi** [comment]
I am afraid I don't entirely understand the problem, can you elaborate @jubaan?

**Comment by jubaan** [comment]
Hi Maciej, no problem... int the microverse pathway when you want to see the quenstions and answers from other students a lateral panel opens showing the threads that have been posted answering that question. but when you want to continue your lecture of the program and want to close this lateral panel it doesnt disapear all the way, it leaves a semitransparent section of the lateral panel. If you see the image you'll see wat i mean.

thank you a lot
________________________________
De: Maciej Nowak <notifications@github.com>
Enviado: martes, 26 de noviembre de 2019 07:07 a. m.
Para: microverseinc/microverse-issue-tracker <microverse-issue-tracker@noreply.github.com>
CC: jubaan <julio.ab@outlook.com>; Mention <mention@noreply.github.com>
Asunto: Re: [microverseinc/microverse-issue-tracker] Group Discussion Panel Doesnt Close (#147)


I am afraid I don't entirely understand the problem, can you elaborate @jubaan<https://github.com/jubaan>?

**Comment by Keqi** [comment]
Hey @jubaan,

Could you please open a Zendesk ticket with the Student Success team to clarify this issue? I am afraid I don't know how to help you.

**Comment by Keqi** [comment]
Closing as there is no response for 9 days.
