### ISSUE TITLE
Requesting un-pairing with a coding partner to work on a collaborative porject

### ISSUE THREAD

**Issue by stratospherique** [microverseinc/microverse-issue-tracker#148]
- Since I reached the last project (i.e bookstore cms) and I allowed my partner to work solo on the last project because microverse asked him to become a full time TSE, I want to know why some of the milestones appear completed in my dashboard ? 

- I have a screenshot of the progress tab on my dashboard. It should describe the situation better.
![image](https://user-images.githubusercontent.com/26124023/69433957-eb979480-0d3c-11ea-9cc4-a12064e66818.png)

* Student success team have told me that the problem is solvable by implementing some back end changes. I hope you find a way to do it :nerd_face: 

Best Regards
_**Ahmed Mahfoudh**_

**Comment by Keqi** [comment]
Hi @stratospherique,

It seems like almost all your `React & Redux` projects are now completed. Perhaps it was marked as completed because the SS team did not re-assign the coding partner in our system. Is everything fine now?

**Comment by stratospherique** [comment]
Yes @Keqi I found out that there is a **unsubmit project** button that I missed. It enabled me to submit code review requests again. So I guess the problem is solved :+1: :+1:
