### ISSUE TITLE
Several false absences

### ISSUE THREAD

**Issue by johnsonsirv** [microverseinc/microverse-issue-tracker#149]
Dates
2019-11-19 
2019-11-11 
2019-11-08

 I was never absent on these days, and have not been absent on any day. I joined the meeting on these days. Somedays, I notice that I am prompted to log in with my email, and on some other days I am not.  I have completed the Onboarding, as I regularly join the meetings on other days without prompt to login.

Particularly I remember joining the meeting after Student Assembly, I don't know why I was tracked as absent.

Kindly fix. Thanks

**Comment by Keqi** [comment]
Hi @johnsonsirv,

According to the system logs, these meetings have never taken place. Do you remember if you joined alone and nobody was there?

**Comment by johnsonsirv** [comment]
Hi @Keqi,

I would say you are right that the meeting didn't hold, because, I joined the meeting and waited for the other team members for a while. For some reason, no other person joined the meeting, so I left. 

I joined, should I be marked as absent? The other day for Assembly, I managed to join from my other device, but my team couldn't because the 'Button' had already disappeared.

Thanks

**Comment by Keqi** [comment]
Hey @johnsonsirv,

If you were alone in the room, and no one else joined, please reach out to the Student Success team and tell them about it. They will create an Absence Request record for you to justify it.

**Comment by johnsonsirv** [comment]
@Keqi this is very frustrating. Several times I try my best to join the meetings even on days I have electricity downtime, I manage to join using a mobile device so I can share progress with the team, and here I am faced with several unnecessary backs and forth. This is time-wasting.
For all I care, this indicates that I should care less about the attending meetings anyway since I have to go through all these over and over again. Well, this is the last time I will create an Issue regarding attendance. 

I attend an event, the system usually detects my individual logs. If the system does not detect any other person's logs and therefore concludes that the meeting never held that is fine, but, I consider being marked as absent a weakness in the system. Asking me to get an Absence Request Record with further justification for an event that I was present is a much more confusing process. How do you justify that?

You should be in a better position to Investigate this and escalate because you are literally also part of the Student Success team. The absences can linger, I care less going forward.
Kindly share with me the logs for those dates if possible, I would like to see that my logs were not captured.

**Comment by Keqi** [comment]
Hi @johnsonsirv,

I am sorry for your frustration. We're improving the detection system and the whole process but it takes time. I assure you, any absence like this where you were the only person at the meeting will not be counted against your progress.

However, for the time being, we have no possibility to erase this absence from the Dashboard, other than submitting an absence request. That's why I asked you to reach out to the Student Success team and describe your problem.

Please, as for now, if you were marked as absent but you were the only one to attend the meeting, ignore it and don't create a ticket. It's something we're working on.
