### ISSUE TITLE
Algorithms & Data Structures mob programming Form has a Bug

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#150]
Hello, the form for the Mob programming has some required fields that you have to skip when you are presenting. So it's impossible to skip them in order to submit the form. Thanks!

**Comment by Keqi** [comment]
Hey @majovainilla,

Currently, the peer-to-peer session and mob programming are experimental forms that aren't finished. Can you please fill these fields with something like `Not applicable`?

**Comment by majovainilla** [comment]
Yes, that could be an option, but the form doesn't allow for that. So what I'm doing is answering the questions even if it's said to skip it.

**Comment by Keqi** [comment]
Please continue to do so. You can also ask Emily to modify the form :)
