### ISSUE TITLE
Cannot access the dashboard

### ISSUE THREAD

**Issue by Joecleverman** [microverseinc/microverse-issue-tracker#152]
I just can't access the dashboard it keep saying that my email or password is wrong but it's not because this is the same I use for everything. Please help!

**Comment by Keqi** [comment]
Hi @Joecleverman,

The dashboard credentials should not be the same as for other accounts (except for Zoom). Have you followed the onboarding materials? You have to reset your password in order to get a password to the Dashboard.

**Comment by Keqi** [comment]
No response for 6 days. Closing.
