### ISSUE TITLE
No Join Call Button

### ISSUE THREAD

**Issue by srueda27** [microverseinc/microverse-issue-tracker#153]
I'm not seeing the Join Call Button 
![image](https://user-images.githubusercontent.com/15695439/69570669-3d832900-0f8e-11ea-856c-883c000908ef.png)

![image](https://user-images.githubusercontent.com/15695439/69570692-4ffd6280-0f8e-11ea-8405-0910e80e46bd.png)

**Comment by sz16900** [comment]
Neither am I ... Help please.

**Comment by uzorjchibuzor** [comment]
@srueda27 @sz16900 is either of you still experiencing this problem?

**Comment by srueda27** [comment]
Sorry, forgot to close the issue, it was solved by registering the email into zoom.
In the Onboarding pathwright there is this step
![image](https://user-images.githubusercontent.com/15695439/69734786-9ae9b800-10fd-11ea-96c5-7bd6c6a93a8c.png)

**Comment by uzorjchibuzor** [comment]
Very good. Thanks for the notification.
