### ISSUE TITLE
Professional skills

### ISSUE THREAD

**Issue by ampaire** [microverseinc/microverse-issue-tracker#154]
My dashboard shows I have not done any professional skills course and yet I had gone up to making my personal portfolio and I was filling in all the forms at the end of the courses

**Comment by Keqi** [comment]
Hi @ampaire,

Have you finished your professional skills before or after November 14? The disclaimer at the top of the page indicates that all submission before November 14 were not yet migrated but we're working on it.

**Comment by Keqi** [comment]
Your progress should now be migrated to the Dashboard :)
