### ISSUE TITLE
Weekly Progress

### ISSUE THREAD

**Issue by damiecode** [microverseinc/microverse-issue-tracker#155]
On Mondays, since we can solve more than one coding challenge, I have noticed the weekly progress increases. For example, I submitted 3 coding challenges and the daily stand up form and my weekly progress is 44% and it is just Monday
![Screenshot from 2019-11-26 02-28-10](https://user-images.githubusercontent.com/29799224/69592021-ee241380-0ff4-11ea-9638-8687d870dc2b.png)
. I suggest coding challenges should not be counted as morning sessions for now since we work on peer to peer code review.

**Comment by Keqi** [comment]
Hi @damiecode,

Peer-to-peer reviews are still in the experimental phase and that is why we haven't decided to make any changes to the Dashboard until concepts are proven. Thanks for noticing the problem, we'll fix it when the morning session will become a stable routine.
