### ISSUE TITLE
I didn't submit any SQL and Ruby on Rails projects

### ISSUE THREAD

**Issue by FelipeEnne** [microverseinc/microverse-issue-tracker#156]
Is a bug 

![print](https://user-images.githubusercontent.com/15949778/69627037-a15a3000-1028-11ea-92a2-d429d0429a57.png)

**Comment by Keqi** [comment]
Hi @FelipeEnne,

It's not a bug. These projects don't require review so we ask you to implement them and then submit the `Project Completion` form.

**Comment by FelipeEnne** [comment]
Ok, thanks
