### ISSUE TITLE
Not able to enter the Technical Questions section

### ISSUE THREAD

**Issue by srueda27** [microverseinc/microverse-issue-tracker#158]
Im trying to get into the Technical Questions section in the Dashboard, but is asking me to log in and it says that my email doesn't match
![image](https://user-images.githubusercontent.com/15695439/69739665-1c454880-1106-11ea-971d-0dcad082faf1.png)

**Comment by Keqi** [comment]
Hi @srueda27,

The credentials used for Questions are different than the ones for the Dashboard. Please follow-up with the Student Success team to register you to the platform.
