### ISSUE TITLE
Zoom Collaborative Call Issue - Joining incorrect meeting

### ISSUE THREAD

**Issue by FreeLydia** [microverseinc/microverse-issue-tracker#16]
Received this from Matheus Lopes da Silva, GH ID: matheus-fls

Hello dear Microverse staff, it's me again. Today I'm having issues with Zoom. The link in the dashboard sends me to my partner's personal room and his link sens him to my personal room, so we can't join the same call using the aforementioned link. We just want to let you know that we are going to join a call without using the dashboard link, so this will probably count as an absence in your system. Thank you for your attention, have a nice weekend!

@Keqi - I haven't heard of this issue happening before! Please look into this. :)

**Comment by ViriCruz** [comment]
I had the same problem this morning with the link in the dashboard for zoom call.

**Comment by Keqi** [comment]
@ViriCruz Is this happening all the time or occasionally?

**Comment by ViriCruz** [comment]
It happened to me just that morning.

**Comment by Keqi** [comment]
@ViriCruz Alright, it seems like a random issue. I'll look into it.

**Comment by Keqi** [comment]
This has been confirmed on Slack with @ViriCruz as fixed. If it ever occurs again, please open a new issue :)
