### ISSUE TITLE
I was in the Standup Zoom room 

### ISSUE THREAD

**Issue by paulgureghian** [microverseinc/microverse-issue-tracker#160]
on 11-25 but was marked absent because the team was in another room breaking in some new students.  I didn't know which room to login to.

**Comment by Keqi** [comment]
Hi @paulgureghian,

Do you remember what was the reason for your team to log in to the other room? No matter what, you should always conduct your meetings in your team's room, otherwise you will be marked as absent.

**Comment by paulgureghian** [comment]
They were breaking in a new group of students and I didn't know anything about it. I was in the team's room. I need that absence removed.

**Comment by Keqi** [comment]
Correct me if I am wrong but this means you joined the room alone because your entire team was in a different one?

**Comment by paulgureghian** [comment]
Yes. and I had no idea

**Comment by Keqi** [comment]
Alright, thanks for the explanation and thanks for your patience waiting for the answer. In this case, this is a false positive which can be erased by submitting the absence request with a specific note describing the problem. Unfortunately, if you were the only person in the room, the system does not record the meeting.

Please, reach out to the Student Success team linking to this issue and asking them to create an absence request for you for the past date.
