### ISSUE TITLE
I have an absence in the system but I did login using the Join Call button

### ISSUE THREAD

**Issue by aecordova** [microverseinc/microverse-issue-tracker#161]
I did Join the standup meeting yesterday, however zoom was acting strange and wasn't opening, after several attempts I had to force close it, then was able to join the call.

Please remove absence as I joined the call.

**Comment by Keqi** [comment]
Hi @aecordova,

Indeed, you were present on this meeting and two others were system marked you as absent. I corrected those. Thanks for the report.
