### ISSUE TITLE
Join Call option unavailable!

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#163]
Hey guys! 

I got repaired today and both me and my partner(Yosept) are unable to see the Join call button on the dashboard.
Requesting the team to fix it soon.

Thank you

**Comment by Keqi** [comment]
Hi @moinkhanif,

Have you followed the onboarding materials? Please read the following document: https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/55314027/

You have to sign-in through https://microverse.zoom.us and this will automatically create your Zoom account with personal links that will appear in the Dashboard. It seems like your current coding partner hasn't done it too. Can you please let him know?

Thanks!

**Comment by YoseptF** [comment]
Hi @Keqi, 
I'm Moin's partner Joseph, nice to meet you. I think I already had made every onboarding material, including login as a student in zoom 
![image](https://user-images.githubusercontent.com/44252641/70173473-7f9c2100-1698-11ea-97dd-565671e84cc4.png)
I was even able to connect with my last partner, and with my teammates on the daily stand up meeting, the problems seem to happen only when I try to work with Moin 
![image](https://user-images.githubusercontent.com/44252641/70173597-cf7ae800-1698-11ea-8ce8-66b4ff7f9098.png)

**Comment by moinkhanif** [comment]
Also @Keqi, I just had to sign out and follow the instructions again and now my account seems to be switched to Microverse. But I still don't get the Join call option.

**Comment by Keqi** [comment]
Hi @moinkhanif, @YoseptF 

You discovered a small bug in our synchronization process which was responsible was linking your Zoom accounts to Student records. You should be able to see your `Join Call` buttons now.

Thanks!
