### ISSUE TITLE
unable to submit my project for code review

### ISSUE THREAD

**Issue by jaspreet-singh-sahota** [microverseinc/microverse-issue-tracker#165]
hey team,

I have try like 15 time when i submit my code it dose not response and the page turn blank(white).
I am unable to progress due to this ,

please solve this issue as soon as possible

**Comment by Keqi** [comment]
Hi @jaspreet-singh-sahota,

Can you please elaborate and tell me what is your issue in detail and if it's still happening?

**Comment by Keqi** [comment]
Closing as there is no response for 7 days.
