### ISSUE TITLE
clockify dose not update my work hrs

### ISSUE THREAD

**Issue by jaspreet-singh-sahota** [microverseinc/microverse-issue-tracker#166]
hey team,

In clockify it only shows my personal workspace, not the Microverse workspace. But in my standup team, everybody have two workspace (personal & the microverse one). 
I have try to log in to microverse workspace from my email but it says that the link has expired.

please solve this issue.
thank you.

**Comment by Keqi** [comment]
Hi @jaspreet-singh-sahota,

From what I can see, you're registering hours and they are visible in the Dashboard. Please re-open this issue if I am incorrect.

Thanks!
