### ISSUE TITLE
I have false detected absence

### ISSUE THREAD

**Issue by Joecleverman** [microverseinc/microverse-issue-tracker#167]
I joined the morning session on November 26th, the system counted me as absent. May someone help me fix that. Thank you.

**Comment by srueda27** [comment]
Same issue. It says that I was absent during the coding morning challenge, which was the first peer-to-peer review of our group and in fact, I presented on that day

**Comment by sz16900** [comment]
Same issue. It shows that I was absent three times in a row, when in fact I have not missed a single day during my first week at Microverse.

**Comment by Keqi** [comment]
HI @Joecleverman,

Could you please send me your email address so I can debug your issue?

@srueda27 @sz16900 Please create separate Github issues so I can handle your individual cases.

**Comment by Keqi** [comment]
Closing as there is no response for 1 month.
