### ISSUE TITLE
Unable to join to the stand up meeting

### ISSUE THREAD

**Issue by duducus** [microverseinc/microverse-issue-tracker#168]
Hey!

My Dashboard doesnt load correctly and the join call button doesnt apperar

Plz help

**Comment by Keqi** [comment]
Hello @duducus,

Can you elaborate on what your issue is? I am afraid I don't really understand. Can you also send me your email address so I can debug it?

Thanks

**Comment by Keqi** [comment]
Closing as there is no response for 7 days.
