### ISSUE TITLE
Unable to join evening sessions

### ISSUE THREAD

**Issue by ferdelvalle** [microverseinc/microverse-issue-tracker#170]
I recurrently have issues to join the evening meetings with my stand up team, I just don't see the join call button, I've tried logging in, out, from another computer, another browser and this keeps happening. It has happened to me on Oct 1st, Nov 5th, 7th, 27th and yesterday.

Is there any good practice to stop this from happening? or a correct way to log in to the dashboard?

**Comment by Keqi** [comment]
Hi @ferdelvalle,

This seems like a weird issue because as you mention, it is arbitrary. It shouldn't be happening in any case. You are assigned to the team so you should see the link.

I'll try to debug your case thoroughly but in the meantime, can you keep your standup link bookmarked?

**Comment by Keqi** [comment]
Closing as there is no response for 7 days.
