### ISSUE TITLE
View progress section ask for some projects to be submited

### ISSUE THREAD

**Issue by jubaan** [microverseinc/microverse-issue-tracker#173]
Projects from the "DATA BASES" and "RUBY ON RAILS" have the status "submit a project", like if I had already submitted for review a previous file. But im not yet in that step of the curriculum im just ending my first week with html.

I'm attaching an image
![Screenshot from 2019-11-29 21-51-30](https://user-images.githubusercontent.com/25774518/69895335-09439b80-12f3-11ea-8019-124880dcc1ee.png)

**Comment by Keqi** [comment]
These projects are non-reviewable and don't require a TSE review. Whenever you complete them, you can submit a Project Completion form.
