### ISSUE TITLE
Wrong absenteeism detection count on my dashboard

### ISSUE THREAD

**Issue by tunedev** [microverseinc/microverse-issue-tracker#175]
I noticed that I am being marked as absent for the meetings that I attended. and I followed the instructions prescribed in the attendance and absences page, yet it still flagged me as absence for the subsequent meetings. Kindly help look into this.

**Comment by Keqi** [comment]
Hi @tunedev,

I don't see any absences in your Dashboard. Our system does not synchronize meeting records immediately but it's a delayed process. Please, stay patient and watch your absences dashboard. If some absence remains there for too long, open an issue.

Thanks!
