### ISSUE TITLE
Broken Link in Pathwright

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#176]
Hello!

I was going through the A & DS curriculum and found this [broken link](https://ruby.unicorn.tv/articles/fibonacci-s-code-recursion-and-memoization-for-ruby-beginners) in the Additional Resources part of the [Basic Recursion Lesson](https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/54137243/)

Thanks!

**Comment by Keqi** [comment]
Hi @majovainilla,

Thanks for your attention to detail. It has already been reported to @nidalaa. We'll fix it soon.

**Comment by gregthepeg4** [comment]
@nidalaa Hey I think that the website we link to has deleted the content. I've searched and couldn't find anything about fibonacci. We will have to find a new resource or just remove the link

**Comment by nidalaa** [comment]
Thank you @majovainilla  and @gregthepeg4 ,

I replaced the broken link with a new one! 💪
