### ISSUE TITLE
I have been banned as absent in sessions that I was present and on time!

### ISSUE THREAD

**Issue by carloshdelreal** [microverseinc/microverse-issue-tracker#18]
I have been banned as absent in many coding challenge meeting and stand up meetings in the last week of August (August 26th to 30th), by that time I was using a different computer because I was visiting my parents and I think that could be the problem.

Then I was banned as absent yesterday in the stand-up meeting (September 10) and I was present and on time!!.

I will appreciate to take out those absences
![Captura de pantalla 2019-09-11 09 51 30](https://user-images.githubusercontent.com/8964341/64708616-7d9c3a80-d47a-11e9-945a-6e210d8ecbc9.png)

**Comment by Keqi** [comment]
Hello @carloshdelreal,

Are you following instructions from that page? The system log says you were present on all these meetings but your email couldn't be found when you joined meetings. That's why we couldn't match you to your Student record.

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
