### ISSUE TITLE
wrongly detected absence on 2019-12-03

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#180]

**Comment by uzorjchibuzor** [comment]
Hi Albert, 

Apologies for the late response, I have made some database corrections regarding the missing absences but for confirmation, the meeting that was counted as absence for you was the standup right?

**Comment by ngodi** [comment]
Yes it was for the stand-up

**Comment by uzorjchibuzor** [comment]
@ngodi please note that the absence for standup on December 03, 2019 have been rerctified. Thanks you.
