### ISSUE TITLE
I have false detected absence

### ISSUE THREAD

**Issue by srueda27** [microverseinc/microverse-issue-tracker#181]
I says that I missed the coding challenge on the 26th of November, but in fact that day I was the one presenting the code.
srueda27@gmail.com

**Comment by uzorjchibuzor** [comment]
Hello @srueda27, 
According to the database, I can see that you are present for the meeting, but it looked like you were not signed in to Zoom when you joined. the correction have been made, please verify that the false absence have been rectified.

**Comment by srueda27** [comment]
I still can see the absent

**Comment by uzorjchibuzor** [comment]
Okay, noted we are going to debug this.

**Comment by uzorjchibuzor** [comment]
@srueda27 the absence recorded for the morning session have been rectified. Thank you
