### ISSUE TITLE
False detected absence

### ISSUE THREAD

**Issue by jabichris** [microverseinc/microverse-issue-tracker#185]
On my dashboard, I am seeing detected absence yet I attended everything.

**Comment by uzorjchibuzor** [comment]
Hello @jabichris,

When are the dates that you are seeing these absences for?

**Comment by jabichris** [comment]
All most every day as you can see in the image below.

<img width="904" alt="Screen Shot 2019-12-17 at 16 39 20" src="https://user-images.githubusercontent.com/33568373/71005305-1e3e6e00-20ec-11ea-815e-01426105f8e5.png">

**Comment by Keqi** [comment]
Hi @jabichris,

I am extremely sorry for the very late response. Our time is very limited recently.

As far as I can see in the system logs, you're appearing in all meetings but it seems like you're either signed in as a guest or as a wrong user. Could you please sign out of your Zoom account and whenever you join the meeting, make sure you're signed in with https://microverse.zoom.us/?

**Comment by Keqi** [comment]
Closing as there is no response for more than 2 weeks.
