### ISSUE TITLE
Mistake in absence&attendances

### ISSUE THREAD

**Issue by 300ms** [microverseinc/microverse-issue-tracker#186]
Yesterday(2019-12-05), i joined to "Stand Up" meeting with my team but today i have an absence for it on my dashboard. A little bit help would be amazing please ^^

**Comment by uzorjchibuzor** [comment]
Hi @300ms,

I don't see your presence at the meeting for the Standup on November 29. If this was a power outage or internet connection issues, please reach out to the Student Success team to clarify your case. They will justify it. You can include the link to this Github issue in the Zendesk ticket.

Thanks!
