### ISSUE TITLE
Mistake in absence

### ISSUE THREAD

**Issue by MotivateJ** [microverseinc/microverse-issue-tracker#187]
On Nov 27th, am marked absent under "Coding challenge meeting". I was present all throughout the day. From the curriculum, you state that, we should start the coding challenges after completing the ruby project. Kindly check into this.

Secondly, It is indeed true that I didn't attend the afternoon stand up meeting because there was power outage, just a few minutes to the meeting. So, what should someone do in such unforeseen circumstance?
Thanks

**Comment by uzorjchibuzor** [comment]
@MotivateJ for the second question, in such cases, reach out to Student Success Team and open a ticket with them. Regarding the absence for the coding challenge, Unfortunately, I don't see any absence on Nov 27th. Is this still correct?

**Comment by MotivateJ** [comment]
Thank you Chibuzor for your response,
On my dashboard, there is still an absence under "Coding challenge meeting" that is on 27th Nov, I think I will assume that for now. In regards to the second issue, I will try and reach the Students Success Team.
I highly appreciate your advise.

**Comment by uzorjchibuzor** [comment]
@MotivateJ on further investigation, I need to ask if you signed into the microverse zoom before joining the call? The system won't recognise that you were present otherwise.

**Comment by MotivateJ** [comment]
Yes, I did. I always do
Thanks

**Comment by uzorjchibuzor** [comment]
@MotivateJ I have corrected the issue in the database, kindly verify if the absence is no longer shown for you. I am closing this issue as resolved, please reopen it if required.
