### ISSUE TITLE
Unable to submit for a review

### ISSUE THREAD

**Issue by jabichris** [microverseinc/microverse-issue-tracker#188]
When I try to submit the work for a review, I am getting this message. Any help on this one?

<img width="838" alt="Screen Shot 2019-12-09 at 10 43 44" src="https://user-images.githubusercontent.com/33568373/70420685-eb9fd000-1a70-11ea-8a45-3d227bd19f40.png">

**Comment by uzorjchibuzor** [comment]
@jabichris To submit a project for a review, we have moved the form away from airtable, you can now submit it [here](https://dashboard.microverse.org/code_review_request/new)
Also, remember that if you work collaboratively with your partner on a project, only one of you should submit this request and it will be counted for both of you. Thank you
