### ISSUE TITLE
Incorrect link to the coding challenge in pathwright

### ISSUE THREAD

**Issue by juzQrios** [microverseinc/microverse-issue-tracker#189]
Pathwright step in Algorithm & Data Structures - https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/54641023/

This step links to the coding challenge from repl.it but it's broken.
Broken link: https://repl.it/student/submissions/7647738

Working link to the coding challenege: https://repl.it/student/submissions/6644894

**Comment by nidalaa** [comment]
Thank you @juzQrios for both - reporting it and leaving precise instructions on how to fix it! <3
