### ISSUE TITLE
I have several detected absences when I was present  in all the detected sessions

### ISSUE THREAD

**Issue by fatymahmed** [microverseinc/microverse-issue-tracker#19]
![Screenshot from 2019-09-10 17-14-57](https://user-images.githubusercontent.com/16196289/64883720-b3067b00-d668-11e9-9092-e23678eca808.png)

Hi @Keqi, I was present in all these calls but unfortunately, I was detected as absent.

**Comment by sabayounis** [comment]
My evening stand up meeting button does not available sometimes so lots of present are marked as absent

**Comment by Keqi** [comment]
Hi @fatymahmed,

Can you please send me your email address privately on the Slack? I'll need it to debug the problem.

@sabayounis Are joining your meetings even if the button is not present for you? If you join them, you shouldn't be marked as absent.

**Comment by sabayounis** [comment]
Okay I'm sending on slack

**Comment by fatymahmed** [comment]
hi @Keqi, Done.

**Comment by Keqi** [comment]
Hello @fatymahmed,

According to the system, you were not absent but you joined these meetings as a guest and we couldn't recognize you. Don't worry, it won't be counted against you but please always make sure to follow the instructions from Attendance & Absences page and sign in through microverse.zoom.us.

**Comment by fatymahmed** [comment]
Hi @Keqi,
Okay, will do so from now on, Thank you.
