### ISSUE TITLE
Algorithms and datastructures in Ruby

### ISSUE THREAD

**Issue by ampaire** [microverseinc/microverse-issue-tracker#190]
I am unable to do the coding challenges in repli.it. I cannot edit anything on my workspace, I have logged out and logged in again but no change. What could be the problem?

**Comment by uzorjchibuzor** [comment]
@ampaire apologies for the challenge you are facing, have you tried clearing your sessions and cookies?

**Comment by ampaire** [comment]
@uzorjchibuzor thank you but I did clears all the sessions and cookies but it doesnt change a thing

**Comment by nidalaa** [comment]
Hi @ampaire ! Can you share the email address of your account in repl.it?

**Comment by ampaire** [comment]
@nidalaa , https://repl.it/@Phemia

**Comment by ampaire** [comment]
@nidalaa  my email address is femayapr@gmail.com

**Comment by nidalaa** [comment]
Hi @ampaire !

I checked your account and everything look good.
Can you check if you try to make a change in already submitted challenge?
Also, does it happen in case of all challenges or only specific ones?
Can you give me an example of challenge that you cannot edit with a screenshot?

**Comment by ampaire** [comment]
@nidalaa , It was in my settings. I found the keybinds were checked for **vim** instead of **default**

**Comment by nidalaa** [comment]
Hi @ampaire !

Thanks for letting us know! :)
