### ISSUE TITLE
Monday 09/012/2019 - Morning session

### ISSUE THREAD

**Issue by WCanirinka** [microverseinc/microverse-issue-tracker#194]
My morning session on Monday is displaying is past due yet I had submitted my form

**Comment by uzorjchibuzor** [comment]
@WCanirinka Thanks for reporting this, I take it that you mean Monday 13th? Could you provide us with a screenshot? Thanks.

**Comment by WCanirinka** [comment]
It was Monday 09th, but I figured that was a bug because it keeps changing on my dashboard so maybe some bugs that are being fixed now.

**Comment by nidalaa** [comment]
Hi @WCanirinka and @uzorjchibuzor ,

according to the announcement fro December 10 https://microverse.zendesk.com/hc/en-us/articles/360040014973-December-10-2019-Algorithms-Data-Structures-Overhaul-stage-3-Mob-Programming

>Important note: "My progress" may not immediately display the correct status of forms submitted in the last few weeks. Please ignore errors as we are still working on them.

I am happy to hear that it works as it should after the change was introduced @WCanirinka ! <3
We will try to get as much historical data as possible in the next weeks!
