### ISSUE TITLE
Wrong absences recorded everyday

### ISSUE THREAD

**Issue by Redvanisation** [microverseinc/microverse-issue-tracker#195]
I false absence issue yesterday and it was fixed in the morning, but I just found out that I have the same issue today too even though I have attended both meetings.
<img width="1179" alt="Screen Shot 2019-12-11 at 8 51 40 PM" src="https://user-images.githubusercontent.com/33462180/70675821-3f204280-1c58-11ea-9d14-f05e4236fec4.png">

**Comment by uzorjchibuzor** [comment]
Hello @Redvanisation,

I could not see any absence in the date that you have sent for both meetings, please reach out to Student Success and use this link for justification. Thanks.
