### ISSUE TITLE
Broken Link in Pathwright

### ISSUE THREAD

**Issue by gregthepeg4** [microverseinc/microverse-issue-tracker#196]
A student reported that when he follows the link to repl it on the page below he gets a 404 page not found error. When I click the link I get sent to a login page and I don't know what credentials to use so I'm passing this to you guys :)

https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/60023443/

**Comment by gootyfer** [comment]
@gregthepeg4 I updated the link and now it's fixed! Please, double-check with the student :)
![unicorn](https://user-images.githubusercontent.com/759396/70792671-08524580-1d9a-11ea-98c9-57cef0617360.gif)
