### ISSUE TITLE
The Challenge links at the Dashboard redirect to the wrong path

### ISSUE THREAD

**Issue by uryelah** [microverseinc/microverse-issue-tracker#197]
![pppp](https://user-images.githubusercontent.com/16193212/70722324-d677ab00-1cd5-11ea-9118-4f83c155a0a2.png)
All the Challenge links that should link to their hackerrank url go to the Algorithms Pathwiright instead.

The sequence of clicks from the Dashboard to the buttons with incorrect hrefs is:
 >View Progress>Codding Challenges>Actions>View Coding Challenge

**Comment by uzorjchibuzor** [comment]
Hello @uryelah,
Thank you for noticing this problem. Our curriculum team will look into it.

**Comment by nidalaa** [comment]
Hello @uryelah ,

Thank you for your report. Linking to Pathwright lesson instead of HackerRank challenge is designed behavior.

It is really important that you read Pathwright lesson before you start solving the challenge.
And inside lesson, you can see a link to all extra challenges as well :)
