### ISSUE TITLE
Big Bug on the Peer-to-Peer Code Review Session

### ISSUE THREAD

**Issue by SofiBretz** [microverseinc/microverse-issue-tracker#199]
### Steps to the get the bug:

- Fill the form as normal, completing all the fields (the optional field: "Do you have anything you’d like to add about this Morning Session? (Optional)" you will get the same result if you fill it or not.)
- Go to the option: "Did the presenter speak loud enough?".
- Select the "No" option.
- Submit the form.
- You will get this message: "Loud enough can't be blank".

It is a bug because "yes" and "no" is an option in this form if the person didn't speak aloud, the option "no" is supposed to work, not to render the page and show a message as if the user didn't fill this option.

This is a big bug because to submit the form successfully the user has to select the "yes" option, in this case, the "no" option is not available to submit the form.

Can you please fix this bug. Thanks! :)

**Comment by uzorjchibuzor** [comment]
Thanks @SofiBretz for reporting this issue, our dev team will look into this.

**Comment by Keqi** [comment]
Hi @SofiBretz,

I am extremely sorry for the very delayed response. Our development resources are very limited at the moment.

We have fixed the bug reported by you. You should be able to select the option `No` now :)
