### ISSUE TITLE
Required signin credentials "each" time I'm to use the Join button to enter a zoom meeting. 

### ISSUE THREAD

**Issue by trekab** [microverseinc/microverse-issue-tracker#2]
Every time I click the JOIN button to join a meeting, I have to first go through the steps on the "attendance and absent" link to sign-in in order to have my attendance reflected on my dashboard. My colleagues were able to do this only once.

**Comment by Keqi** [comment]
@trekab Are you sure you are not signed out from the Zoom account? In normal conditions, you should sign in once by following the instructions in the Attendance & Absences page and then be able to join meetings,

**Comment by sebastianlujan** [comment]
I had the same issue with zoom some times.

**Comment by trekab** [comment]
@Keqi I faced a similar issue again today as I tried to use the JOIN button to start the meeting with my coding partner. I had to re-open the microverse.zoomus page and just refresh the page. That's what gave me my access to the meeting.

**Comment by Keqi** [comment]
Your session might have expired and therefore you had to re-join again. It's standard procedure.

**Comment by trekab** [comment]
Oh! That makes sense. Thanks!
