### ISSUE TITLE
Wrongly recorded absences

### ISSUE THREAD

**Issue by codingAngarita** [microverseinc/microverse-issue-tracker#20]
Hi, on the detected absences tab I see a total of 13 stand-up meeting absences, I have linked my zoom account as requested and I haven't had any issues joining these meetings, I also access them through the link on the dashboard. here are all the absences.

![image](https://user-images.githubusercontent.com/44899916/64716852-c65af000-d488-11e9-80ec-c8db49f49bc6.png)

**Comment by Keqi** [comment]
Hi @codingAngarita,

Are you following instructions from the Attendance & Absences page? You may have to sign out and sign in again via Microverse Zoom account.

**Comment by codingAngarita** [comment]
Hi @Keqi,

I followed the instructions when the feature got released, but I just completed the steps again just in case

**Comment by Keqi** [comment]
Hey @codingAngarita,

Are you still being marked as absent on all Standup meetings or did it stop?

**Comment by codingAngarita** [comment]
Hi @Keqi!

It stopped marking me as absent on the recent standup meetings, the absences are the same as in the picture I attached

**Comment by Keqi** [comment]
Hey @codingAngarita,

I am glad to hear that it stopped marking you as absent. It shouldn't anymore because Zoom enforces sign-in state before joining meetings now.

Please ignore these past absences. They won't be counted against you.
