### ISSUE TITLE
Wrong absences from 2019-12-09 to 2019-12-13

### ISSUE THREAD

**Issue by kalavhan** [microverseinc/microverse-issue-tracker#200]
I'm Irwing Josué Brigido Espinoza
The system added absences from 2019-12-09 to 2019-12-13, in both, coding challenge and stand up meeting, even though i was in all the meetings.
i opened zoop desktop and i discovered that i wasn't signed in, this has anything to do? and if it is the case what can i do to fix the absence problem.
Thanks a lot in advance, have a nice day!

**Comment by kalavhan** [comment]
i opened microverse.zoom.us and i discovered that i wasn't signed in, this has anything to do? and if it is the case what can i do to fix the absence problem.
Thanks a lot in advance, have a nice day!

**Comment by Keqi** [comment]
Hi @kalavhan,

I am extremely sorry for the very late response. Our development resources are very limited recently.

It seems like your absences are gone from the Dashboard. Is there anything else we can do for you?

**Comment by kalavhan** [comment]
Hi @Keqi, thanks for the answer, everything it's fine now, the problem was indeed with the fact of me not being signed in in microverse.zoom.us
