### ISSUE TITLE
wrong absence in 06-12-2019

### ISSUE THREAD

**Issue by mohamednaser** [microverseinc/microverse-issue-tracker#201]
I attended a morning meeting in 06-12-2019 and it counts as an absent 

![absent (1)](https://user-images.githubusercontent.com/6272923/70935313-95222b00-2048-11ea-8eba-1e9a38d1a95d.png)

**Comment by uzorjchibuzor** [comment]
Hi @mohamednaser,

Did you have internet challenges on this day? or maybe you were being disconnected? You were indeed present according to the database, kindly reach out to Student Success and you may link this issue for justification. Thanks
