### ISSUE TITLE
"Hours Registered" has reset to 0!

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#202]
Hey team,

In the Microverse [Dashboard](https://dashboard.microverse.org/dashboard), the hours registered seems to be showing 0 since today morning(17-Dec-2019). I checked Clockify and everything seems to be fine there. 
Attached the screenshot below: 

![Annotation 2019-12-17 200908](https://user-images.githubusercontent.com/6555800/71005333-80f23280-2109-11ea-86e7-5c43d0b32952.jpg)

**Comment by uzorjchibuzor** [comment]
@moinkhanif Thanks for reporting this,

Our development team will look into this.

**Comment by moinkhanif** [comment]
Whoa! I suppose the issue is resolved. I am able to see the registered hours now 👍 . Thank you for fixing it soon team!
![Annotation 2019-12-18 200801](https://user-images.githubusercontent.com/6555800/71095166-296bc980-21d2-11ea-9304-ae0bc5d10cba.jpg)
