### ISSUE TITLE
Dashboard "Hours Registered" reset to 0.

### ISSUE THREAD

**Issue by KerronKing** [microverseinc/microverse-issue-tracker#203]
Good day,

The "hours registered" on my dashboard in the "my stats" section has been reset to zero.

**Comment by KerronKing** [comment]
![Screenshot 2019-12-17 at 3 11 56 PM](https://user-images.githubusercontent.com/49284298/71026475-b4b86280-20df-11ea-82fe-f96d1b09e3a1.png)

**Comment by uzorjchibuzor** [comment]
@KerronKing Thanks for notifying us, our dev team will look into this and fix the issue for you. Thanks.

**Comment by Keqi** [comment]
Hi @KerronKing,

I am extremely sorry for the very late response. Our development resources are very limited recently.

It seems like your registered hours are back to normal count :) Closing this issue.
