### ISSUE TITLE
Cannot acces the zoom meeting afternoon

### ISSUE THREAD

**Issue by Joecleverman** [microverseinc/microverse-issue-tracker#206]
I was not able to access the stand-up meeting on Wednesday 18th, 2019 because the button did not show up

**Comment by Keqi** [comment]
Hi @Joecleverman,

I am extremely sorry for the very late response. Our development resources are very limited recently.

Can you see your `Join Call` button now? Usually, this kind of problems appears on your first day in Microverse or when you're repaired.

**Comment by Keqi** [comment]
Closing as there is no response for 7 days. Please, re-open this issue if this problem keeps occurring.
