### ISSUE TITLE
#Team-71 - Morning Standups for Code Review should be 1 hour

### ISSUE THREAD

**Issue by simonpeterdebbarma** [microverseinc/microverse-issue-tracker#207]
First of all, _we love having standup_. It makes us feel accountable, and I think my group are very tight knit already, in less than a month.

However, we do have **one issue** and I've seen this in a couple teams that joined in November like us. We got used  to hour-long standups in the morning and that gave us ample time to review code, write issues, and share tips or feedback. Since it was shortened to 30 minutes, a lot of us are finding it a little hard as we having to rush through the process, leading to _bad code review_. 

Most of the time we end up having standup for 40-50 mins, either way; and meet our partners around 8:45 a.m. (on average).

#### Here's an example :
**[1 hour code review](https://github.com/mariosknl/form_cloning/issues/3) vs [30 min code review](https://github.com/codecell/apple-retro-page/issues/2)**

We believe it would be much more beneficial for us to have 1 hour allotted for code review.

**Comment by nidalaa** [comment]
@simonpeterdebbarma Thank you for this issue!

The peer-to-peer code review session was designed for 30 minutes from the beginning (I blame delayed changes in the dashboard for confusion here). 
The most beautiful thing about code review is - that it can be a neverending story - there is always something to improve or to be done with a different approach :)

That is why we wanted to limit you - it will also give you a little training to discuss with your team which points are the most important to address! 

Please - give this approach a try and check if doing a decent code review is possible if you keep time discipline as described https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/64608260/.

However - we are really interested in this feedback and we would like to explore it more with more students!

@gregthepeg4 could you transfer this issue to feature request, so we can take other students' comments and votes in one place?

**Comment by gregthepeg4** [comment]
Moved

**Comment by nidalaa** [comment]
@gregthepeg4 can you share a link here ? :)

**Comment by gregthepeg4** [comment]
https://microverse.zendesk.com/hc/en-us/community/posts/360037964434-Changes-to-standups
