### ISSUE TITLE
Improvement for morning sessions

### ISSUE THREAD

**Issue by davidauza-engineer** [microverseinc/microverse-issue-tracker#208]
It could be a good idea to either allow some teams to work on the coding challenges as before, and continue working individually on them on Mondays, or to allow working on a side project together as a team. That would be definitely more exciting, rewarding and motivating that current half on hour meetings which are so short to do something worth

**Comment by gregthepeg4** [comment]
I have moved this to the zendesk feature request section

**Comment by davidauza-engineer** [comment]
Thank you very much @gregthepeg4  :)
