### ISSUE TITLE
Broken link on Pathwright Coding Challenge

### ISSUE THREAD

**Issue by frederico-miranda** [microverseinc/microverse-issue-tracker#209]
There is a coding challenge on pathwright which leads to a broken link. It's the following one.

**Assignments 5.2 Stacks or Recursion**

![Screenshot_2019-12-24_18-08-12](https://user-images.githubusercontent.com/11416855/71425203-ddf56780-2678-11ea-9cf0-2f5716d14b93.png)

The link is this one: https://repl.it/student/submissions/9925327

After clicking on the link, it leads to an "404 Not Found" page.

![Screenshot_2019-12-24_18-12-23](https://user-images.githubusercontent.com/11416855/71425236-fe252680-2678-11ea-91c1-9db75f717edb.png)

**Comment by nidalaa** [comment]
Thank you for your report @frederico-miranda. Link has been corrected https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/60023443//
