### ISSUE TITLE
Confusion over linters config

### ISSUE THREAD

**Issue by bolah2009** [microverseinc/microverse-issue-tracker#212]
## Description of issue

There is currently nowhere in the pathwright that says students shouldn't change linters config but only to set it up, this causes confusion between students and TSEs during code reviews.

## Proposed Solution

* [ ] As discussed on slack, it would be better to have _an explicit comment in [this lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)_
* [ ] In addition, a comment about it should be added to the **Remember to** section of each project specification.

**Comment by uzorjchibuzor** [comment]
@bolah2009 Thanks for opening this issue.

**Comment by nidalaa** [comment]
Thank you @bolah2009 
- linked lesson has been updated
- additional comment was added to all readme files in linters-config repo (this repo is linked in each project).
