### ISSUE TITLE
Project not approved marked as approved

### ISSUE THREAD

**Issue by AndresFMoya** [microverseinc/microverse-issue-tracker#213]
Good day. 

My Weather app project is still under review by TSEs but I don’t have the option to request a new Code Review. It’s in `Submit Project` Status.

Please switch the status to: `request code review.`

Thanks.

**Comment by nidalaa** [comment]
Hi @AndresFMoya !

Thanks for your report - it should be fixed now! Can you confirm?

**Comment by AndresFMoya** [comment]
Hi @nidalaa. Now it’s fixed! Thanks!
