### ISSUE TITLE
Wrongly Detected Absence 01/06/2020

### ISSUE THREAD

**Issue by euqueme** [microverseinc/microverse-issue-tracker#214]
I have a wrongly detected absence for both the coding challenge and standup meetings from yesterday

![image](https://user-images.githubusercontent.com/52209067/71901155-ed6abb00-3124-11ea-861b-fed908902d5d.png)

**Comment by Keqi** [comment]
Hi @euqueme,

I am extremely sorry for the very late response. Our development resources are very limited recently.

It seems like your wrong absence was corrected by the system. Sometimes, it takes several hours to synchronize data between Zoom and our database and this could be a reason why you saw the absence.
