### ISSUE TITLE
 404 error for "Is it a Search Tree?"

### ISSUE THREAD

**Issue by gregthepeg4** [microverseinc/microverse-issue-tracker#215]
I am getting error 404 for "Is it a Search Tree?" as well. The links are as follows;

https://repl.it/student/submissions/9245319 hosted on https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/54577960/

As reported by Gerald Goh

**Comment by nidalaa** [comment]
Thanks @gregthepeg4 ! Fixed 💯
