### ISSUE TITLE
Fix layout for screens smaller than 1920 in the Coding Challenges section of the Dashboard

### ISSUE THREAD

**Issue by nurislam-ab** [microverseinc/microverse-issue-tracker#216]
For the table of coding challenges at the screens smaller than 1920px, title and completion time are becoming not readable.
http://joxi.ru/823XdwWiD6bvwA

As a solution I could suggest using `white-space: normal` for the rows
http://joxi.ru/EA4xLwdtOD6VWA

I would be glad to know if there are more appropriate ways to solve this.

**Comment by Keqi** [comment]
Hi @nurislam-ab,

I am extremely sorry for the very late response. Our development resources are very limited recently. Thank you for your attention to UI details. We've applied your little fix. You have made your first indirect contribution to the Microverse dashboard! Congratulations :)
