### ISSUE TITLE
Project completed not showing on dashboard

### ISSUE THREAD

**Issue by gregthepeg4** [microverseinc/microverse-issue-tracker#217]
Nurislam Abdurasulov (Nurislam) has submitted a project with his partner but it is not showing up on his dashboard. Please could you make it so that the highlighted project is marked as complete for him?
This is the was the pull request
https://github.com/nurislam-ab/smashing_magazine/pull/5

His  coding partner was Marshall Chikari

![Capture](https://user-images.githubusercontent.com/28516574/71989456-ff864f80-3231-11ea-9a77-40edfcadb5fb.PNG)

**Comment by Keqi** [comment]
@gregthepeg4 I've messaged you directly with the solution to the problem. Closing.
