### ISSUE TITLE
Past due stand up forms do not submit/save on first go

### ISSUE THREAD

**Issue by Rhelli** [microverseinc/microverse-issue-tracker#218]
Hi there,

I've had a couple of evenings where I've forgotten to submit my daily stand up form and have left it to the next day where I am presented with the yellow 'Past Due' alert to submit the previous day's stand up form. However, on completing the form, submitting it, and refreshing the page, it often appears to still display 'Past Due' with a yellow notification. It normally requires 2 or 3 submissions to turn green and give me the 'Submitted' message.

**Comment by Keqi** [comment]
Hi @Rhelli,

I am extremely sorry for the very late response. Our development resources are very limited recently.

This sounds like a very interesting issue. Could you please record the video the next time it happens. I would love to reproduce it myself and be able to fix the issue.

Thanks!

**Comment by Rhelli** [comment]
Hi Maciej,

No worries at all, thanks for getting back to me!

It may be a tricky one to capture as it's inconsistent however, I believe that I know the specifications to trigger it. It normally occurs when I have two (identical) iterations of the Microverse Dashboard open in Chrome and when the form submission button is in a yellow state.

I'll leave my  evening form submission for this evening and try to reproduce it tomorrow though.

All the best,

Rory

**Comment by Rhelli** [comment]
Hi @Keqi ,

As a quick update, I've tried to reproduce the bug a number of times however I haven't seen it since so it's seems likely that it was a local error. That being said, I'll close the issue for now so it's one less thing on the list!

All the best,

Rory
