### ISSUE TITLE
Some clarification needed on the React Calculator project Milestone 4.

### ISSUE THREAD

**Issue by jofer86** [microverseinc/microverse-issue-tracker#219]
- For this issue, I need to provide some context first, in point number 2, the last paragraph has these instructions
![image](https://user-images.githubusercontent.com/46115725/72095439-13878b00-32de-11ea-8337-7774fd591baf.png)

- In point number three, the last paragraph has these instructions 
![image](https://user-images.githubusercontent.com/46115725/72095555-4df12800-32de-11ea-90dd-b16ffe9d6526.png)

- This might bring a point of confusion as to the actual use of the '%' key in this project, we could use it as modulo as it is somewhat implied in the second screenshot, or we can use it as a modifier as it is used more widely by calculators.

As a TSE and as a student this might bring a topic of debate because it is not as clear as to what we need to require as TSE's and what we need to fulfill as students.

------------------------
## Proposed Solution
- As the actual use in a calculator is to make use of the % key as a modifier, meaning turning the number into a percentage based number I.E `95 % == .95` . I would suggest just a small addition to [milestone 4](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896094/), in order for  that particular issue to be clear

**Comment by nidalaa** [comment]
Thanks @jofer86 ! 😍 

Already fixed 💪
