### ISSUE TITLE
I have an absense when I've been present

### ISSUE THREAD

**Issue by IvanDerlich** [microverseinc/microverse-issue-tracker#22]
I have an absence for yesterday's standup meeting when actually I was present

**Comment by Keqi** [comment]
Hey @IvanDerlich,

Can you specify which day it was and which meeting(s) you were marked as absent?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
