### ISSUE TITLE
Student Dashboard Home Page Presents a Server Error Message

### ISSUE THREAD

**Issue by Bluette1** [microverseinc/microverse-issue-tracker#220]
# Student Dashboard Home Page Presents a Server Error Message

- This is what I see when I log into the [Student Dashboard](https://dashboard.microverse.org/dashboard)

> Server Error
Congratulations, you just broke the Microverse site. You can be proud of yourself! Don't worry, our dog guard is on the watch debugging what has just happened...

- Also at this point there is no "Join Call" link showing for the scheduled welcome call on the 13th of January. I don't know if that is expected.

**Comment by Keqi** [comment]
Hi @Bluette1,

I am extremely sorry for the very late response. Our development resources are very limited recently.

Do you still experience this issue? It could have been related to the onboarding process when you join Microverse on your first day. We always deal with some or bigger problems.

**Comment by Bluette1** [comment]
Hello Maciej,

Thank you for your response! This issue had been fixed by the first day
when I started at Microverse . I think it was related to the onboarding
process. I am grateful for your prompt response.

Kind regards,

Marylene
