### ISSUE TITLE
Microverse Dashboard Server Error

### ISSUE THREAD

**Issue by sddoe** [microverseinc/microverse-issue-tracker#221]
This is what I see when I log into the Student Dashboard:

"Server Error
Congratulations, you just broke the Microverse site. You can be proud of yourself! Don't worry, our dog guard is on the watch debugging what has just happened"

**Comment by Keqi** [comment]
Hi @sddoe,

I am extremely sorry for the very late response. Our development resources are very limited recently.

Is this still happening to you? This usually happens when students join Microverse on their first day. During that time, we often deal with some small or bigger problems.

**Comment by sddoe** [comment]
You are right! It was happening only during the first days. Thanks a lot for your response!
