### ISSUE TITLE
Meetings and daily schedule appear active during weekends

### ISSUE THREAD

**Issue by wickathou** [microverseinc/microverse-issue-tracker#222]
For some reason the daily schedule appears active during weekends.
![image](https://user-images.githubusercontent.com/50066876/72205525-26bb6780-3452-11ea-8e32-2597baff9147.png)

**Comment by Keqi** [comment]
Hi @wickathou,

Haha, nice catch! Well, you're not supposed to work on weekends so don't look at your Dashboard :) We'll look into it in the free time but the severity of this bug is low so I can't promise it will quickly be fixed.

**Comment by wickathou** [comment]
Of course 😁I knew it’s not a priority but found it interesting. Javier Hernandez From: Maciej NowakSent: Thursday, January 23, 2020 5:20 AMTo: microverseinc/microverse-issue-trackerCc: Javier Hernandez; MentionSubject: Re: [microverseinc/microverse-issue-tracker] Meetings and daily schedule appear active during weekends (#222) Hi @wickathou,Haha, nice catch! Well, you're not supposed to work on weekends so don't look at your Dashboard :) We'll look into it in the free time but the severity of this bug is low so I can't promise it will quickly be fixed.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
