### ISSUE TITLE
Progress to be reset to start in January.  

### ISSUE THREAD

**Issue by Genius8** [microverseinc/microverse-issue-tracker#223]
I had recently withdrawn from the November class and am now starting the January class, but my dashboard still indicates November progress and absences. Help me out here. Thanks.

**Comment by kotoku-code** [comment]
me and my partner are having the same issue and is not letting us submit our first project

**Comment by Keqi** [comment]
Hi @Genius8 @kotoku-code,

I am extremely sorry for the late response. Our Dev resources are limited recently.

It seems like your issue has been solved by the Student Success team. Please feel free to respond or close this issue.

**Comment by Keqi** [comment]
Closing as there was no response for more than a week.

**Comment by Genius8** [comment]
Thank you so much for the assistance.
