### ISSUE TITLE
Pathwright project page > Broken link found for Code review Request form 

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#226]
Hey team,

In the Pathwright Project description, it links to a private Airtable link instead of the dashboard form when we click on "code review request form", which is available in "Once your project is ready" todo section.

**Comment by nidalaa** [comment]
Hi @gregthepeg4 can you handle this? 🙏 

This is an example of the project https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/ (heads-up: all projects will need this update).

And this is a correct link https://dashboard.microverse.org/code_review_request/new .

**Comment by gootyfer** [comment]
I fixed all the links to the code review request correct link ;)
