### ISSUE TITLE
Pathwright 1st html & css project request clarification

### ISSUE THREAD

**Issue by dili021** [microverseinc/microverse-issue-tracker#227]
one of the requests is to add the recommended video thumbnail previews which causes a bit of confusion with whether or not it needs to be just an image (like it says on TOP) or an actual video preview.

**Comment by nidalaa** [comment]
Hi @dili021 !

I remember your report from slack, you used screenshots there to explain  what is the problem in details 😍 
In the future please remember to include all useful information in the issue as well :)
