### ISSUE TITLE
DETECTED ABSENCES

### ISSUE THREAD

**Issue by FelipeEnne** [microverseinc/microverse-issue-tracker#228]
They detected my wrong absence on 2020-01-10.
I was the only one of my group that appeared, I don't think it's fair to punish myself for it.

**Comment by Keqi** [comment]
Hi @FelipeEnne,

I am extremely sorry for the very late response. Our development resources are very limited recently.

In such a case, please reach out to the Student Success team and use the link to this issue. They will manually add an absence request for you and justify your "absence".

**Comment by FelipeEnne** [comment]
Sorry, you can send me a link for he Student Success team

Em qui., 23 de jan. de 2020 às 07:26, Maciej Nowak <notifications@github.com>
escreveu:
