### ISSUE TITLE
Dashboard > Deprecated Project from Pathwright Not updated in the dashboard

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#229]
Hey team,

One of the HTML projects(Design your own Grid-based Framework) has been recently deprecated to make way for the HTML/CSS Capstone Project. However, the dashboard "View Progress" page still shows the old grid-based layout project.

Should we request a code review using the currently available list or should we have to wait till its updated?

Pathwright link: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/

Dahboard: ![Annotation 2020-01-14 212429](https://user-images.githubusercontent.com/6555800/72359524-6e711600-3714-11ea-80bb-9e1de8a6a8f5.png)

Pathwright:
![Annotation 2020-01-14 212453](https://user-images.githubusercontent.com/6555800/72359525-6e711600-3714-11ea-9102-eca948be7107.png)

Thank you

**Comment by gootyfer** [comment]
Hi @moinkhanif ,

There will be a student announcement about this topic soon :) 

If you finished the project (Design your own Grid-based Framework) you can request a code review from dashboard like always. I'll explain more in detail in the announcement.

Thanks for reaching out.
Best regards,
Israel
