### ISSUE TITLE
I have an absence from 2019-09-10

### ISSUE THREAD

**Issue by ViriCruz** [microverseinc/microverse-issue-tracker#23]
Hello, I have an absence from yesterday standup meeting date 2019-09-10, it happened before too. I was in the meeting and also my teammates were in the meeting and some of them have the same absence from yesterday. I think this is a very important bug to solve.
![image](https://user-images.githubusercontent.com/5501777/64734663-e5af4880-d49b-11e9-860d-1ab1997acc29.png)

**Comment by Keqi** [comment]
Hey @ViriCruz,

Can you send me your email address privately on Slack so I can debug your issue? Thanks!

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)

**Comment by ViriCruz** [comment]
thank you, I don't have any false absences now. Also sorry not to send my email I didn't realize you message me. I hope this problem is fixed for every student :).
