### ISSUE TITLE
Issues In Trying To Join Call With My Stand up Team

### ISSUE THREAD

**Issue by adewaleK** [microverseinc/microverse-issue-tracker#230]
I am a new student and I have been having issues when trying to join call with my stand up team. I could only see myself in the call each time I tried to join.

**Comment by gregthepeg4** [comment]
Hi @adewaleK can you confirm if this is still an active issue or has this now been resolved?
If this is still an issue please email success@microverse.org with a link to this bug request.

**Comment by Keqi** [comment]
Closing as there was no response in 9 days. @adewaleK, please feel free to re-open if this is still a problem for you.
