### ISSUE TITLE
Unable to Request for A Code Review from the TSE

### ISSUE THREAD

**Issue by Bluette1** [microverseinc/microverse-issue-tracker#232]
Hey Team,

We are unable to open the link to the [code review request form](https://airtable.com/shrVqH0c0PkuLWIgi) in the microverse main curriculum on [microverse pathwright ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/).

Similar to issue #226

Thank you

**Comment by Keqi** [comment]
Hi @Bluette1,

The link to the Code Review Request has been fixed. Thanks for your nice catch.
