### ISSUE TITLE
Code Review Request Bug

### ISSUE THREAD

**Issue by KerronKing** [microverseinc/microverse-issue-tracker#234]
Good Day, my dashboard is displaying the following behaviour after submitting for a code review:
![Screenshot 2020-01-16 at 7 33 04 PM](https://user-images.githubusercontent.com/49284298/72571897-452cc300-3897-11ea-941a-1d34d984af6f.png)

Please assist.

**Comment by Keqi** [comment]
Hi @KerronKing,

It seems like we have discussed this issue on the slack channel. It is fixed now :)
