### ISSUE TITLE
Submit Project Bug

### ISSUE THREAD

**Issue by Audrey-Ella-xo** [microverseinc/microverse-issue-tracker#236]
Hi, Reviewer
My partner and I finished a project yesterday, and we submitted the project for a code review. But instead of getting a review, the status of our project changed to "submit project" and we didn't get a review done. Here is the screenshot of the problem;

![image](https://user-images.githubusercontent.com/54140453/72625440-1b33d900-3949-11ea-9f68-1cbca8683f43.png)
Kindly advise us on the way forward, thanks

**Comment by euqueme** [comment]
@Keqi 
we appreciate some feedback to this bug is been 4 days already and we really don't want it to be marked as invalid because we didn't get a code review.

**Comment by Keqi** [comment]
Hi @Audrey-Ella-xo, @euqueme,

I am sorry for the very delayed response. We're extremely limited by the Dev resources.

Indeed, there was a glitch in the record because this code review request was marked as approved but your TSE left you comments about it. Weirdly, there are no comments in the PR itself but he left you comments in the Code review request record. I am pasting it here (sorry for the bad formatting):

```
## Changes Required.\r\n" +
"\r\n" +
"Hi team!\r\n" +
"\r\n" +
"There are few updates to make:\r\n" +
"\r\n" +
" ##### `edit` action: add an edit action to your user controller and route.\r\n" +
"\r\n" +
" - [ ] finds user based on id from params, i.e. @user = User.find(params[:id]) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))\r\n" +
"\r\n" +
"##### `update` action : Add update action to your controller and routes\r\n" +
"\r\n" +
"* [ ] finds user based on id from params, i.e. `@user = User.find(params[:id])` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_params.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))\r\n" +
"* [ ] `redirect_to edit_user_path` if user was saved\r\n" +
"* [ ] `render :edit` if user was not saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))\r\n" +
"\r\n" +
"Also, implement a view for edit action ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_edit.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))\r\n" +
"\r\n" +
"### After implementing these updates, submit another form for a code review.\r\n" +
"\r\n" +
"#### ``` Have a great day ``` :slightly_smiling_face: \r\n" +
"\r\n" +
"``` Uchechukwu Henry Inyama ```
```

Could you message him and clarify the review if you can't read it from here?

**Comment by euqueme** [comment]
Thank you @Keqi 

It reads just fine but we'll contact Henry if necessary, also the status of the project has changed to Changes Required, so this Issue is solved for us. :raised_hands:
