### ISSUE TITLE
Write your first article pathwright

### ISSUE THREAD

**Issue by dili021** [microverseinc/microverse-issue-tracker#237]
Suggestion to relocate the "write your first article" step from step 6 to step 3 in the professional curriculum.

**Comment by Keqi** [comment]
Hey @nidalaa @gootyfer,

Is this something under your supervision? :)

**Comment by gregthepeg4** [comment]
Hi @dili021,

Thanks for this feedback. Unfortunately, this is not the right place to post feedback so I will followup with you via email.

Warm regards

Greg
