### ISSUE TITLE
I cant send my friday morning session form

### ISSUE THREAD

**Issue by Daniduran-dev** [microverseinc/microverse-issue-tracker#238]
Every time I submit the form I get an error:
![Opera Snapshot_2020-01-18_205937_dashboard microverse org](https://user-images.githubusercontent.com/57133486/72664887-970b4f80-3a35-11ea-8c07-51531eace217.png)

**Comment by Daniduran-dev** [comment]
I know better whats the issue. you cant answer NO to the question of the presenter speaking loud enough. Every time you select NO it won't let you submit the form.

**Comment by Keqi** [comment]
Hi @Daniduran-dev,

This issue has been fixed an hour ago. Sorry for the inconvenience.
