### ISSUE TITLE
day - 6 still not re-paired and no response to my pervious issue

### ISSUE THREAD

**Issue by jaspreet-singh-sahota** [microverseinc/microverse-issue-tracker#239]
even thou I was the 1st one to complete the projects and asked for re-pairing in my stand-up team.
everyone from my stand-up team has been re-paired and I am still waiting for mine.
I hope microverse team will soon fix this problem.

Thank you.

**Comment by gregthepeg4** [comment]
Closing this issue as student should keep working with current partner
