### ISSUE TITLE
Pathwright > Two Re-pair requests at the end of HTML/CSS section

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#240]
Hey team,

I noticed that there were two re-pair requests at the end of HTML/CSS path:

- Instance 1: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54656843/
- Instance 2: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/65938510/

![Annotation 2020-01-20 220756](https://user-images.githubusercontent.com/6555800/72744105-f18de280-3bd2-11ea-9290-08a297330205.png)

Given that we need to finish two professional skills before requesting a re-pair, I believe the first one needs to be removed to avoid confusion.

Also, I'd like to add that the lesson names given in the below section(Instance 2) are different from the one in the pathwright professional skills. It would be great if they could be updated to the ones given in the professional skill curriculum:

![Annotation 2020-01-20 220908](https://user-images.githubusercontent.com/6555800/72744322-577a6a00-3bd3-11ea-9511-aebc317df32e.png)

Thanks for your support!

**Comment by Keqi** [comment]
Hey @nidalaa @gootyfer,

Is this something you could look into? :) Thanks!

**Comment by gregthepeg4** [comment]
Hi @moinkhanif, Thanks for pointing out the issue with the multiple re-pair steps. We have removed the re-pair from Advanced CSS3. I have also updated the titles of the projects to make the instructions more useful.

Thanks for being such a proactive student :)
