### ISSUE TITLE
Detected absence for 2020-01-20

### ISSUE THREAD

**Issue by ViriCruz** [microverseinc/microverse-issue-tracker#241]
I have an absence for 2020-01-20 even though I attended the meeting. Why is this happening?

**Comment by Keqi** [comment]
Hi @ViriCruz,

It seems like your absence is gone. The system synchronizes data with the Zoom API every few hours so it may turn out that you see your absence immediately after you finished your meeting. Please, be patient, if you attended the meeting, the absence will eventually disappear.

**Comment by ViriCruz** [comment]
Hi @Keqi , thanks for the information, I didn't know that. I will be aware of.
