### ISSUE TITLE
TSE Code Review Panel Problem

### ISSUE THREAD

**Issue by trox115** [microverseinc/microverse-issue-tracker#242]
Hello, in Code Reviews requests. I received a project, I review it and I approved the project. When I was going to leave a comment I noticed that it had already been review (2 times). Don't know how is it possible to say that it was a first review project when it was already reviewed(but it is maybe some bug).
Claim ID: 18961
Here is the screenshot
![download](https://user-images.githubusercontent.com/1369941/73000262-802f7900-3df8-11ea-8ba3-04d350c49560.jpeg)

**Comment by nidalaa** [comment]
Hi @trox115 !

I will close this issue as it is not related to student dashboard - let's continue in a proper place.
