### ISSUE TITLE
Angelist Profile Project Page Missing Content

### ISSUE THREAD

**Issue by KerronKing** [microverseinc/microverse-issue-tracker#244]
Good day,

In working through the professional skills curriculum, I stumbled upon the "How to Build a Solid AngelList Profile (Project: Creating a Great AngelList Profile)" page. As shown in the screenshot below, the content on this page is not rendering properly beyond the title and the "complete step" button. I'm not sure if this is a bug solely on my machine or if it's a general issue so I just wanted to highlight it.

![Screenshot 2020-01-27 at 4 53 08 PM](https://user-images.githubusercontent.com/49284298/73213170-1da2e980-4126-11ea-8a5c-e7e8288e959e.jpg)

**Comment by Keqi** [comment]
Hi @KerronKing,

Do you still see a blank page? I can see content on this page so I am wondering if the page wasn't filled before or was it a one-time page load problem on your side.

https://microverse.pathwright.com/library/microverse-professional-development-37fa36d5/90738/path/step/68916393/

**Comment by KerronKing** [comment]
It seems to be working fine now. Thanks for the response!
