### ISSUE TITLE
Wrong absence detected

### ISSUE THREAD

**Issue by damiecode** [microverseinc/microverse-issue-tracker#246]
I just realized I was marked absent on the 24th of this month for the stand up meeting and I was present in the meeting

**Comment by Keqi** [comment]
Hi @damiecode,

It seems like nobody was present at the meeting except you. Is this correct? This is a flaw in our system which doesn't record meetings with just one participant. Can you reach out to the Student Success team to create the past absence request for you? You can link to this GH issue to provide them more explanation.

**Comment by damiecode** [comment]
Hello @Keqi , all my standup team members were present during the meeting but we were all marked absent. We think it is because we completed the standup that day very fast so it was marked absent for us.

**Comment by Keqi** [comment]
Hi @damiecode,

It's weird. I don't really know why the system has marked you all as absent at this meeting. I fixed it manually.
