### ISSUE TITLE
Wrong absences detected

### ISSUE THREAD

**Issue by Audrey-Ella-xo** [microverseinc/microverse-issue-tracker#247]
I just noticed that I have a detected absence from yesterday's stand up meeting, but I was present.

Kindly help me to correct this. Thank you

**Comment by Keqi** [comment]
Hi @Audrey-Ella-xo,

It seems like you were the only participant at the meeting, correct? In such a case, please reach out to the Student Success team to create an absence request for you. Our system does not record a meeting that has less than 2 participants.

Thanks!

**Comment by Keqi** [comment]
Closing as there is no response for more than 7 days.
