### ISSUE TITLE
Submitting Project Issue

### ISSUE THREAD

**Issue by Dandush03** [microverseinc/microverse-issue-tracker#248]
I'm trying to get repairs and basically I just got an email saying I didn't submit a project from a professionals skill (which I did)... and when I opened my dashboard and went to the professional skill section I found out that 3 of the project I already submitted still say pending and when re-submeeting them the status quote doesn't change.. The project I finished and it didn't mark as complete are: Article 1, Build a Profesional GitHub && Ethics Profile. please let me know if anyone knows a solution to this issue
here I will post a link for each one of them.

Article #1(Submitted 5 days ago): https://hackernoon.com/learning-css-grid-layout-basic-concepts-with-example-y79w36tk
Ethics Profile (submitted earlier today): https://sway.office.com/3kyfY6mq3egdGaI3?ref=Link
Build a professional Github Profile:( I can't remember how long ago i did this.) https://github.com/Dandush03
before writing this email.. I re-submit all of them.. and I still say it's pending. 

please advise me how should I proceed

**Comment by Keqi** [comment]
Hi @Dandush03,

It seems like these projects are already marked as completed in your Dashboard. It could have been a little delay in our synchronization process which fetches data from 3rd party sources and integrates it into the Dashboard.

I am closing this issue but feel free to re-open it if there is anything else you want to discuss or explain :)
