### ISSUE TITLE
Two false detected absences

### ISSUE THREAD

**Issue by mosesogwo** [microverseinc/microverse-issue-tracker#25]
I have been wrongly detected to be absent on 27th August and 2nd September, 2019.
I am sure I was properly signed in.
Thanks.

**Comment by Keqi** [comment]
Hi @mosesogwo,

Thanks for your report. I checked the system logs and:

For 27th August it seems like meeting did not happen at all or you were the only person in the meeting. Is that correct?

For 2nd September, it was a bug in the system and I manually fixed it for you.

**Comment by mosesogwo** [comment]
Okay.
I am not very sure of what happened on 27th. I am only sure I wasn't absent.
Thank you for the fix.
