### ISSUE TITLE
Professional Projects still marked as pending.

### ISSUE THREAD

**Issue by vieiramanda11** [microverseinc/microverse-issue-tracker#250]
Hello!

I've submitted three professional projects:
 * Personal portfolio
 * Third article
 * Resume

 All of them are still marked as pending.

**Comment by Grifo89** [comment]
Yes, I've had the same issue. 😔

**Comment by Grifo89** [comment]
I keep having the same issue and there is not answer.

**Comment by vieiramanda11** [comment]
> I keep having the same issue and there is not answer.

Hey. If you need these projects approved in order to go along with the course send a message to student success about it. I needed it to do this in order to get my new coding partner. This issue is happening with a lot of people and get it too long to being fixed.

**Comment by Keqi** [comment]
Hi @vieiramanda11, @Grifo89,

Are you still seeing these projects in the `pending` state? We had a little trouble with the synchronization process but it seems to be alright now. Feel free to close this issue if the problem was solved.
