### ISSUE TITLE
Wrong Detected Absences

### ISSUE THREAD

**Issue by Audrey-Ella-xo** [microverseinc/microverse-issue-tracker#251]
I was wrongly marked absent from the morning meeting on the 29th of January and the stand-up meeting on the 30th of January but I attended both meetings. 

Please help me affect the corrections
![image](https://user-images.githubusercontent.com/54140453/73756684-45b6cc00-4768-11ea-84d7-e12b48765d76.png)

**Comment by ViriCruz** [comment]
I have the same wrong absence of Jan 29 for the morning meeting.
![image](https://user-images.githubusercontent.com/5501777/73853843-bdc7d500-47ee-11ea-994d-e48d91a2f159.png)
Also for the 4th of Feb, which I found that other student have the same wrong absence for that day.

**Comment by Keqi** [comment]
Hi @Audrey-Ella-xo,

It seems like our system couldn't find you in the meeting on Jan 29, are you sure you joined the correct meeting. In the case of Jan 30, I explained in the separate issue you created.

@ViriCruz Could you please create a separate GH issue so I can debug your problem separately? :)

**Comment by Keqi** [comment]
Closing as there is no response for more than 7 days. Please, re-open this issue if you want to add more to the discussion.
