### ISSUE TITLE
Wrong Absence Reported

### ISSUE THREAD

**Issue by srueda27** [microverseinc/microverse-issue-tracker#253]
I have two reported absences and I've been in every meeting and call everyday. 
One for the 30th of January and the other for 4th of February

**Comment by ViriCruz** [comment]
I have one of 4th of February too 
![image](https://user-images.githubusercontent.com/5501777/73853260-d1bf0700-47ed-11ea-9d4c-02fec896c9d8.png)

Even though I was on the meeting, what happened to me is that when I clicked the Join button through dashboard, zoom asked me to sign in again with my credentials which I did, with my student dashboard credentials. I think that everytime zoom ask me to login, the system counts it as absense but this is only an assumption. It happened to me twice, I have wrong absence from Jan 29 too.

**Comment by srueda27** [comment]
For the absence of the 4th (yesterday) what I guessed is that we join to the meeting without clicking the join button. We knew that the link was the same for all our standup meetings, so we use it some time before the actual standup.
So I'm guessing that they counted it as absent because we did not click the "Join Call" button, but we were on the call and we had the standup.

**Comment by simonpeterdebbarma** [comment]
I want to appeal to the team at Microverse to kindly remove my false absent detection too. I did email Student Success a couple days back but haven't heard anything so far. Here's a copy of the explanation I sent, which supports the reason by @srueda27.

**Feb 4, 2020**
After my teammates mentioned they had an absent from yesterday, I checked the Attendance & Absences  page to find that I got it too. We were all there, except for one. I have the Zoom room link saved on my Slack, so when my teammates called for some assistance in the afternoon, I gave them the link and we hung out there from 3PM or so, until we were done with Standup. If the morning link and evening link for our Zoom rooms are not the same, that would explain the reason for all us being marked as Absent.

**Jan 24, 2020**
If I recall correctly, I was a little late to the meeting on that particular day, but I did join in about 10-15 minutes past 5PM. It's up to you to decide if that warrants for an Absent, but I don't think it should.

![image](https://user-images.githubusercontent.com/31207418/74037209-7292fb00-4983-11ea-8c92-4ea8750f46bb.png)

- - -

Here's a screenshot of a personal log I keep of my days at Microverse. The column between Hours Spent and Language is - Meetings and Forms Submitted, respectively. You can also check my Clockify and verify the same.

![image](https://user-images.githubusercontent.com/31207418/74037485-f9e06e80-4983-11ea-9091-66737b43ba06.png)

**Comment by EdCrux** [comment]
I have the same issue, but I click the join button

**Comment by Keqi** [comment]
Hi @srueda27,

It turns out that one of your team colleagues is joining these meetings very early, about 2-3 hours before the schedule which falsely assigns the time when the meeting has started. Could you talk to your team about it and make sure you're joining the correct meeting room at the correct time?

Thanks!

**Comment by simonpeterdebbarma** [comment]
Hi @Keqi 

We assumed as these rooms were open all the time, we could use them to hang out together if need be; which is why we logged in our room to discuss code. 

Of course, we could make our own rooms but we have a 45 min limit on them so we resorted to using our Team rooms. 

Could Microverse make it such that teams are able to use their Zoom rooms whenever need be?

Thank you :)

**Comment by alvp01** [comment]
Hello @Keqi I have two registered absences for the days 18 and 19 of Frebuary, but I joined those meetings. Could please check it? Tahnks in advance
![photo_2020-02-20_10-17-36](https://user-images.githubusercontent.com/54279503/74946248-62d9d480-53cf-11ea-93ac-813238251355.jpg)

**Comment by Keqi** [comment]
Hi @simonpeterdebbarma,

It's fine if you join these rooms to freely talk about the program and code. However, you must remember to leave the room and re-join it again at the time of the standup so your meeting record is correctly saved in the DB.

**Comment by simonpeterdebbarma** [comment]
Hello @Keqi

That's fantastic to hear. Thanks for the update.

**Comment by Keqi** [comment]
Hey @srueda27 @simonpeterdebbarma,

Please let me know if we can close this issue.

**Comment by simonpeterdebbarma** [comment]
Hello @Keqi 

You can close this issue, as it's been resolved.
