### ISSUE TITLE
Wrong absence again, date 2020-02-05

### ISSUE THREAD

**Issue by ViriCruz** [microverseinc/microverse-issue-tracker#254]
I clicked join call through dashboard, even though I don't know why the system marked it as an absence.

**Comment by Keqi** [comment]
Hi @ViriCruz,

Is it possible that you were the only participant in these meetings? In such a case, those meetings are not recorded by the system and you are falsely marked as absent. If that's the case, please reach out to the Student Success team to create an absence request records for you for these past dates.

**Comment by Keqi** [comment]
Closing as there is no response for more than 7 days.
