### ISSUE TITLE
false absence detected on 29/01/2020 

### ISSUE THREAD

**Issue by Ashah15** [microverseinc/microverse-issue-tracker#255]
There has been a false detection of absence on this date since i was attending the plagoarism meeting on this particular day.

**Comment by Keqi** [comment]
Hi @Ashah15,

We're clarifying this issue with the Student Success team. I'll get back to you when we have more information. In the meantime, please don't feel worried about this absence. It won't be counted against your progress.

**Comment by Ashah15** [comment]
okay thank you for your assistance

**Comment by Keqi** [comment]
Hi @Ashah15,

It seems like the system did not see you at the Assembly meeting. This is very likely caused by the fact that you joined a guest. Could you please follow-up on this issue with the Student Success team and ask them to create an absence request record for you for this day?

**Comment by Keqi** [comment]
Closing as there is no response for 7 days.
