### ISSUE TITLE
Absence registered in the day of the General Assembly

### ISSUE THREAD

**Issue by majovanilla** [microverseinc/microverse-issue-tracker#257]
Hello, I would like to request the removal of the absence I have on Jan 29th, since that's the day we attended the General Assembly at the same time of the morning call.

Thank you!

**Comment by Keqi** [comment]
Hey @majovanilla,

We're working with the Student Success team to massively fix this issue for many students. Please be patient. In the meantime, don't feel worried about it, this false absence won't be counted against you in any way :)

**Comment by Keqi** [comment]
Hi @majovanilla,

Your issue should be resolved. We modified the code to remove absences for people who participated in the Assembly meeting.
