### ISSUE TITLE
No 'Join Call' option

### ISSUE THREAD

**Issue by praz99** [microverseinc/microverse-issue-tracker#259]
My partner Rajkumar Das and I both are not getting an option to join the meeting in the student dashboard. I have used the same credentials for both zoom login and the dashboard login. It was not there in the morning call also so we just used the zoom call and not after the lunch break still nothing is showing up.

**Comment by Keqi** [comment]
Hi @praz99,

Normally, it will take some time to synchronize Zoom data with our Dashboard. Can you confirm this is still happening to you?

**Comment by praz99** [comment]
Hi Nowak,
The issue has been resolved today. Thank you very much for your time to
reach me out and fixing this issue.

Regards

Prajwal
