### ISSUE TITLE
Incorrect Absences Recorded

### ISSUE THREAD

**Issue by wathigo** [microverseinc/microverse-issue-tracker#26]
I was reported absence on both 10th and 11th of September for both meeting but I attended both meetings. Please look into this.

**Comment by Keqi** [comment]
Hi @wathigo,

I see a lot of absences in the system and most of them are because you're joining meetings as a guest. Have you followed the instructions provided on the "Attendance & Absences" page?

**Comment by wathigo** [comment]
Hi @Keqi,

I just checked the new content added to the onboarding materials. 
Do I have to use the personalized link on my profile to join a meeting with my Stand up team or does it only apply to meetings with my partner?
I have already created an account with the same authentication credentials as my dashboard.
I also join the stand up meeting using the link on the dashboard. 
Currently, I don't have a coding partner so I don't do collaborative calls.

**Comment by Keqi** [comment]
Hey @wathigo,

All you have to do is to make sure are signed in to the microverse.zoom.us before you join any meeting. It does not matter whether you join clicking on the button in the dashboard or using bookmarked link, you just have to be signed in so our system can detect you :)

**Comment by wathigo** [comment]
Hi @Keqi ,

It's now clear. I will let you know if there are still absences after this.
Thank you :)
