### ISSUE TITLE
I can't see the join call button

### ISSUE THREAD

**Issue by LOctavio** [microverseinc/microverse-issue-tracker#260]
My partner and I can't find the join button on the Dashboard.
I have done all the steps and I can't see the button yet.

**Comment by Keqi** [comment]
Hi @LOctavio,

Normally it takes some time to synchronize Zoom data with our Dashboard so the link is accessible. Can you confirm this is still a problem?

**Comment by LOctavio** [comment]
I can join now, thanks.
