### ISSUE TITLE
I can't see the join call button in Collaborative Learning

### ISSUE THREAD

**Issue by Bekhzod96** [microverseinc/microverse-issue-tracker#261]
I have accomplished all steps and logged in with Microverse account as it was asked.
But still no button on dashboard

**Comment by Keqi** [comment]
Normally it takes some time to synchronize Zoom data with our Dashboard so the link is accessible. Can you confirm this is still a problem?

**Comment by Bekhzod96** [comment]
No problem solved, Thanks
