### ISSUE TITLE
Broken link on "[MANDATORY] [repl.it] Stacks on Recursion" lesson

### ISSUE THREAD

**Issue by luis-novoa** [microverseinc/microverse-issue-tracker#263]
Good afternoon,

on [this class](https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/60023443/), the link to the Repl.it class is broken. It is pointing to (https://repl.it/student/submissions/10304006) when it should point to (https://repl.it/student/submissions/10957058).

Best regards,
Luis Novoa

**Comment by Keqi** [comment]
Hi @luis-novoa,

Thanks for your report. It has been fixed :)
