### ISSUE TITLE
Wrong absense detect

### ISSUE THREAD

**Issue by shjang7** [microverseinc/microverse-issue-tracker#266]
![image](https://user-images.githubusercontent.com/40674031/74960652-11bdf500-5450-11ea-96c1-3566d764d7c4.png)
I didn't absent for those days. And you could check form submission too.
Could you kindly check these wrong absent detections?

**Comment by Keqi** [comment]
Hi @shjang7,

Is this possible that you were the only person present in the room? If you were the only participant in these meetings, our system will not record it and thus, you'll be falsely marked as absent. Please, reach out to the Student Success team to retroactively create absence requests for these days for you.

Sorry for the inconvenience.

**Comment by shjang7** [comment]
@Keqi , 
As you said, I tried to submit a form for those days at today, it says I cannot submit for past days.
[Absence request form]
![image](https://user-images.githubusercontent.com/40674031/75222271-2d762200-57e7-11ea-9037-f711cff688cd.png)
Is there the other way to submit it?

**Comment by gregthepeg4** [comment]
Hey @shjang7 I have cleared your absences :)

**Comment by shjang7** [comment]
Thanks @gregthepeg4
