### ISSUE TITLE
Detected Abscence for Feb 18th and 19th, 2020.

### ISSUE THREAD

**Issue by NewIncome** [microverseinc/microverse-issue-tracker#267]
I have detected absences for the Coding Challenge Meeting and Standup Meeting for the 18th and 19th.
I did attend both meetings, both days and also submitted the corresponding forms for each. My team saw me, something must be wrong.
Please help.

Regards,

**Comment by Keqi** [comment]
Hi, @NewIncome 

Is this still a problem? I don't see these absences anymore. It is possible that our synchronization services haven't fetched the most recent meetings from API and therefore marked you as absent. In such a case, please be patient, they will go away.

If your absences remain in the Dashboard for more than 48 hours, then you should create an issue and seek for our support.

**Comment by NewIncome** [comment]
Hi,

Sorry for the delay. But yeah, everything is going great now. They dissapeared after a couple of days.

Kind regards,



J Alfred C P
Title
Company

________________________________
