### ISSUE TITLE
No access to microverse questions

### ISSUE THREAD

**Issue by AlfredoElizarraras** [microverseinc/microverse-issue-tracker#269]
![imagen](https://user-images.githubusercontent.com/28496529/75119345-bc4c3880-5647-11ea-8b57-44b392c8c4ed.png)
Even trying with the email that I use to login in the dashboard it says that it don't match.

**Comment by Keqi** [comment]
Hi @AlfredoElizarraras,

Our Discourse Dashboard uses its own authentication system. I think you have to separately sign up for the platform. For more information, please look into onboarding materials.

@nidalaa Please correct me if I am wrong.

**Comment by AlfredoElizarraras** [comment]
Hi @Keqi,
Thanks for your answer in advance.
So, well how can I sign up there? It also didn't recognize the email that I have been using from the start, I have a look at the on boarding material and only find the way to login zendesk

**Comment by gregthepeg4** [comment]
Hi @AlfredoElizarraras , I have just sent you an email to elizarrarasalfredoog@gmail.com inviting you to join discourse. Make sure you check your spam folder :). If you don't receive it please email me at success@microverse.org :)
