### ISSUE TITLE
I have an absence from 2019-09-09

### ISSUE THREAD

**Issue by Anna-Myzukina** [microverseinc/microverse-issue-tracker#27]
Please check this error. I was present and I with coding partner was all day in call.
![absent_error](https://user-images.githubusercontent.com/26605804/64782013-e663df80-d56c-11e9-9e05-ea63992b2d6f.png)

**Comment by Keqi** [comment]
Hi @Anna-Myzukina,

Thanks for your report. That was a bug in the system which I manually fixed for you :)
