### ISSUE TITLE
A&DS curriculum 5.2 Stacks or Recursion repl.it

### ISSUE THREAD

**Issue by euqueme** [microverseinc/microverse-issue-tracker#270]
The link in the pathwright is not right it should be this one

https://repl.it/student/submissions/11087998

![image](https://user-images.githubusercontent.com/52209067/75175818-a8acda80-56f8-11ea-9212-8de784b186e8.png)

instead of this one

https://repl.it/student/submissions/10957058

![image](https://user-images.githubusercontent.com/52209067/75175976-ec074900-56f8-11ea-8ae2-b8c65b6dbb3c.png)

**Comment by Keqi** [comment]
Hi @euqueme,

Thanks for your catchy eye. Could you send me a link to Pathwright where there is a wrong link? I'll correct it.

**Comment by euqueme** [comment]
sure @Keqi this is the link in pathwright were I found the error:

https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/60023443/

**Comment by Keqi** [comment]
Hi @euqueme,

I changed the link. Thanks again :)
