### ISSUE TITLE
Professional skills progress view not updating status

### ISSUE THREAD

**Issue by jubaan** [microverseinc/microverse-issue-tracker#271]
I have submitted twice two forms from different 'professional skills' projects and the progress view is no updating the status from 'pending' to 'complete.

The two projects form were 'Take a professional photo' and 'asking great questions'

the forms of both projects work fine and after submission show the message that the form has been submitted correctly

**Comment by Keqi** [comment]
Hi @jubaan,

These form submissions are synced between systems with a little delay. Let's in several hours if this is still a problem. If it is, I'll investigate it further.

**Comment by jubaan** [comment]
Well, the thing is I submitted this project's more than a month ago...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Keqi** [comment]
@jubaan I am extremely sorry for my lack of response in recent days. Our development team is very busy.

It seems like those two projects are now marked as `Completed`. If this ever happens to you again, please open a new GH issue or re-open this one and I'll jump quicker to investigate what is the real cause.

**Comment by Keqi** [comment]
Closing as there is no response for 9 days.
