### ISSUE TITLE
Lucky can't submit his project completion form because his partner submitted the project as a solo project (we think)

### ISSUE THREAD

**Issue by gregthepeg4** [microverseinc/microverse-issue-tracker#272]
Hi team!
Lucky's dashboard is asking him to submit a code review request for the Design Teardown project but the project is already approved by the TSE. I sent this to Emily and she said it looks like his partner Stefan submitted the review as a solo project. She suggested that you guys need to change this in the DB for us to allow Lucky to submit the project completion form.

Lucky's Dashboard: https://dashboard.microverse.org/projects?utf8=%E2%9C%93&student_email=aremu.baba70%40gmail.com&commit=View+Progress

The pull request: https://github.com/dili021/Design-teardown/pull/2#event-3008945475

**Comment by Keqi** [comment]
Hi @gregthepeg4,

Can you ask Lucky to go to https://dashboard.microverse.org/project_completions/new, select the `Design Teardown` project and fill out the form? This will convert the status of this project in his progress page.

**Comment by gregthepeg4** [comment]
Done, thanks Maciej :)
