### ISSUE TITLE
Zoom issue: "This Meeting is for authorized attendees only" only during the last meeting of the day

### ISSUE THREAD

**Issue by DennisOsido** [microverseinc/microverse-issue-tracker#273]
![zoomfeb27](https://user-images.githubusercontent.com/58547943/75422439-8674c000-5977-11ea-9e45-c5c9b56a43ec.png)

- Greg of Student Succes has advised me to submit an issue for this.
- I am joining the meetings by clicking on the "Join Call" button from the dashboard.
- I am logged in using the microverse.zoom account
- This is an everyday occurrence. It only happens during the last meeting of the day.
- My theory is that it does this because I am already on a different day vs my other teammates. In that example above. I am on Feb. 27 while my teammates are still in Feb. 26. My time zone becomes 1 day ahead at 5:00 pm UTC -1 (that is 12:00 am of the next day for me).

**Comment by Keqi** [comment]
Hi @DennisOsido,

Unfortunately, there is not much we can do in this case. It seems like Zoom is overly reactive to the authorization process and asks you to sign in too many times. It has nothing to do with the schedules of our students or the implementation of the `Join Call` button.

Please, try to reach out to the [Zoom Support](https://support.zoom.us/hc/en-us) and describe your problem. They are very responsive and usually help debug the issue.

**Comment by Keqi** [comment]
I am closing this issue as there is no response for 7 days.
