### ISSUE TITLE
Retrospective dashboard button has deactivated color.

### ISSUE THREAD

**Issue by uryelah** [microverseinc/microverse-issue-tracker#274]
The retrospective button, though it's working is grey.

Grey is a color usually associated with de-activated buttons.

For a better UX it would be nice to have the button in a more saturated color like green or blue.

![Screenshot_2020-02-28 Dashboard](https://user-images.githubusercontent.com/16193212/75597870-b35bcc80-5a76-11ea-981e-8d548b9ab142.png)

**Comment by Keqi** [comment]
Hi @uryelah,

Thanks for your report. We have fixed the issue :)
