### ISSUE TITLE
Pathwright: some links in bookstore project are wrong 

### ISSUE THREAD

**Issue by men32z** [microverseinc/microverse-issue-tracker#275]
the milestone 1 and 4 "Original version" links send to  "raw" github version instead the actual github link. example 
this
`https://raw.githubusercontent.com/microverseinc/project-redux-bookstore/master/milestones/MILESTONE_1.md`
should be 
`https://github.com/microverseinc/project-redux-bookstore/blob/master/milestones/MILESTONE_1.md`

**Comment by Keqi** [comment]
Hey @men32z,

Thank you for your attentive eye. We have fixed links.
