### ISSUE TITLE
The select TSE menu not working for medium-small screens

### ISSUE THREAD

**Issue by uryelah** [microverseinc/microverse-issue-tracker#276]
I, like many other students, only have one screen to work with.

So sometimes I like to split it so that I can work on two windows at the same time.

When you have a medium size screen (~700px) the TSE select for the submit project form does not work.

It shows up with only two visible options and does not scroll.

![Screenshot_2020-03-06 Project Completion Form](https://user-images.githubusercontent.com/16193212/76085296-820c6080-5f90-11ea-9ba3-cb34e2af7186.png)

Making it work on smaller screens would be the form more accessible. 
Thanks for considering it.

**Comment by Keqi** [comment]
Hi @uryelah,

Indeed, several pages are not very responsive to different screen sizes. The TSE select is an external JS component we integrated into the code. It seems like it doesn't support media queries.

I'll look into it, however, given the current load on our development time, we might not be able to fix it soon. Please, stay patient.

Thanks!
