### ISSUE TITLE
Broken link on "[MANDATORY] [repl.it] Is it a Search Tree?" lesson

### ISSUE THREAD

**Issue by luis-novoa** [microverseinc/microverse-issue-tracker#277]
Good afternoon,

on [this class](https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/54577960/), the link to the Repl.it class is broken. It is pointing to (https://repl.it/student/submissions/10304216) when it should point to (https://repl.it/student/submissions/11377895).

Best regards,
Luis Novoa

**Comment by gootyfer** [comment]
Fixed! Thanks @luis-novoa for reporting!

![eyes](https://user-images.githubusercontent.com/759396/76777331-56675280-67a8-11ea-8a4a-31f80d762472.gif)
