### ISSUE TITLE
Small typo on a lesson from the Professional Skills curriculum

### ISSUE THREAD

**Issue by davidauza-engineer** [microverseinc/microverse-issue-tracker#278]
There is a small typo on the lesson titled: Working through Conflict (Project: Draft a Message to Resolve Conflict) of the Professional Skills Curriculum

The link shown displays `Grammerly`, while the name of the applications is actually `Grammarly`:

<img width="803" alt="Screen Shot 2020-03-11 at 11 57 24 AM" src="https://user-images.githubusercontent.com/47565678/76442838-802b0e80-638f-11ea-91cb-cc0f1b9993d6.png">

**Comment by Keqi** [comment]
Hi @davidauza-engineer,

Thanks for spotting that. It has been corrected.
