### ISSUE TITLE
Microverse.org Dashboard and Questions don't share the same login

### ISSUE THREAD

**Issue by wickathou** [microverseinc/microverse-issue-tracker#28]
Not sure if that's a bug or was made like that by design, but Questions and Dashboard don't have the same login info, so we need to create a separate account for each.

**Comment by Keqi** [comment]
@FreeLydia This is a good point. Is there anything we can do about it?

**Comment by arielcamus** [comment]
@keqi we have to enable SSO in Discourse with Auth0.

**Comment by Keqi** [comment]
Hey @wickathou @arielcamus,

This has been accounted for our backlog and will be considered to prioritize. Unfortunately, it's not an easy change so it might take a while to implement it. I'll keep you posted.
