### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by davidauza-engineer** [microverseinc/microverse-issue-tracker#280]
On the main curriculum lesson called: `Submit: Professional Skills Lessons: Writing Your First Technical Article`, the link shown below redirects to a non-existent URL:

<img width="789" alt="Screen Shot 2020-03-12 at 11 17 02 AM" src="https://user-images.githubusercontent.com/47565678/76542491-0e1bfd80-6453-11ea-8271-6d5e7742cdc5.png">

<img width="1281" alt="Screen Shot 2020-03-12 at 11 17 14 AM" src="https://user-images.githubusercontent.com/47565678/76542498-12481b00-6453-11ea-820d-1ed3ad643757.png">

It points to: `https://dashboard.microverse.org/projects_progress`, but I think the right URL should be: `https://dashboard.microverse.org/projects`

Thanks

**Comment by Keqi** [comment]
Hi @davidauza-engineer,

Could you please paste a link to the Pathwright lesson?

Thanks

**Comment by davidauza-engineer** [comment]
Sure, it is:

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/65938509/

**Comment by Keqi** [comment]
Fixed. Thanks, @davidauza-engineer :)
