### ISSUE TITLE
Incorrect absence recorded

### ISSUE THREAD

**Issue by trekab** [microverseinc/microverse-issue-tracker#3]
On the 2019-09-02, the system flagged me as absent yet I was present.

**Comment by ampaire** [comment]
I have been recorded absent ever since. I  signed in with my microverse credentials

**Comment by imhta** [comment]
On the 2019-08-01, the system flagged me as absent yet I was present.

**Comment by Keqi** [comment]
@ampaire @imhta 

Can you please create separate GH issues so I can handle each problem individually?

**Comment by Keqi** [comment]
@trekab The system says you were present on the meetings on 2019-09-02 but your email was not detected. It seems like you signed in as a guest to the morning session. Were you signed in through Microverse Zoom like described in the instructions?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. If you still see false absences, please create new GH issue describing a problem :)

**Comment by ampaire** [comment]
Thank you 😊
