### ISSUE TITLE
detected absence in 2019-08-23

### ISSUE THREAD

**Issue by serdg0** [microverseinc/microverse-issue-tracker#30]
I have a detected absence on the 2019-08-23, but still i never missed any of the meetings that day.

**Comment by Keqi** [comment]
Hi @serdg0,

There are three absences in the system detected for your account:

August 23rd - corrected in the system
September 5th - system detected your absence in the logs
September 13th - corrected in the system

Are you following the instructions from the Attendance & Absences page? According to the system, you are always signed in to your meetings as a guest. Please sign out of your Zoom account and use microverse.zoom.us to sign in again.

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
