### ISSUE TITLE
Basic Routes, Views and Controllers link to TOP not working

### ISSUE THREAD

**Issue by dili021** [microverseinc/microverse-issue-tracker#304]
The link from project Basic Routes, Views and Controllers (RoR) that sends to The Odin Project isn't working. 
[Here's the link](https://www.theodinproject.com/courses/ruby-on-rails/lessons/basic-routes-views-and-controllers) and [here's the result](https://www.theodinproject.com/courses/ruby-on-rails/lessons/basic-routes-views-and-controllers). Here's the [pathwright step](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/37867374/).

**Comment by nidalaa** [comment]
Hi @dili021 ,

thank you for your report.

As The Odin Project is in the middle of changes in Rails module, we added a note at the beginning of the PAthwright lesson that leads to the new project.
