### ISSUE TITLE
Marking Absent

### ISSUE THREAD

**Issue by sabayounis** [microverseinc/microverse-issue-tracker#32]
My evening standup meeting button some time does not work that's why lots of meeting mark as absent. I sent the screenshots to Willow and she said report the issue.

I hope you guys resolve this issue and mark absent as present.

**Comment by Keqi** [comment]
Hello @sabayounis,

Our system logs tell me you were present on all these meetings but you joined them as a guest. Please, make sure you follow the instructions from the Attendance & Absences page and sign to microverse.zoom.us before you join the call.

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
