### ISSUE TITLE
Several ABSENCES

### ISSUE THREAD

**Issue by euqueme** [microverseinc/microverse-issue-tracker#33]
Hello, I have Absences on 5 days and I haven´t missed a single day since I started on Microverse: 
# | Date            |   | Coding Challenge Meeting | Standup Meeting
1 | 2019-09-12 |   |                                             | ABSENT
2 | 2019-08-28 |   | ABSENT                               |  
3 | 2019-08-14 |   | ABSENT                               | ABSENT
4 | 2019-08-13 |   | ABSENT                               | ABSENT
5 | 2019-08-12 |   | ABSENT                               | ABSENT

you can ask my standup team we are **team-45-the-heliums** on slack

**Comment by Keqi** [comment]
Hi @euqueme,

Could you please send me your email address privately on Slack so I can debug your absences problem?

**Comment by Keqi** [comment]
Hi @euqueme,

I must admit your case is pretty unusual :) Let me elaborate:

August 12 - 14: It seems like meetings were not tracked at all for your entire team. Is it possible that you joined wrong Zoom rooms with your team?

August 28: You joined as a guest to the room and therefore our system couldn't detect you. Please make sure to sign-in via microverse.zoom.us to be properly detected.

September 12: This was a failure in our system which I manually fixed. You shouldn't see that absence anymore.

**Comment by euqueme** [comment]
Thank you @Keqi 

I see you've deleted the absences for September 12 and August 12 how I make the other absences disappear:

August 13 and 14: we had another team in our call showing us how to conduct the morning and evening meetings I'm sure we log to these meetings using the join meeting on the Dashboard thats all I can say about these days but I can assure everybody was there.

 August 28: I don´t know why I join as a guest but since I clearly was there what can I do to make it disappear should I request and absence for this day even though I was in the meeting?

**Comment by Keqi** [comment]
Hi @euqueme,

I have corrected your absence for August 28. For Aug 13, 14, please ignore them for now. They won't be counted against you and we are working to fix all past false absences.

Thanks :)
