### ISSUE TITLE
Several Absences

### ISSUE THREAD

**Issue by fedgut** [microverseinc/microverse-issue-tracker#34]
Hello! I got a ton of absences, arround 85% of meetings are marked as abscent. I did the zoom/microverse account linking when it was required, but still seeing mostly absences. 

1 | 2019-09-12 |   | Absent |  
-- | -- | -- | -- | --
2 | 2019-09-11 |   | Absent | Absent
3 | 2019-09-10 |   | Absent | Absent
4 | 2019-09-09 |   | Absent | Absent
5 | 2019-09-06 |   | Absent | Absent
6 | 2019-09-05 |   | Absent | Absent
7 | 2019-09-03 |   | Absent | Absent
8 | 2019-09-02 |   | Absent |  
9 | 2019-08-30 |   | Absent |  
10 | 2019-08-29 |   |   | Absent
11 | 2019-08-28 |   | Absent | Absent
12 | 2019-08-27 |   | Absent | Absent
13 | 2019-08-26 |   | Absent | Absent
14 | 2019-08-14 |   |   | Absent
15 | 2019-08-12 |   | Absent

**Comment by Keqi** [comment]
Hi @fedgut,

According to the system logs, you were present at these meetings but signed in as a guest. Here's what I would like you to do:

1) Sign out of your Zoom account
2) Visit microverse.zoom.us
3) Sign in using your Dashboard credentials

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
