### ISSUE TITLE
I have 18 absents.

### ISSUE THREAD

**Issue by Vashiramusa** [microverseinc/microverse-issue-tracker#36]
I have attended all meetings since we started the program. But, the
platform shows me that I have 18 absents. I don't want to see the absents on my dash board. Because is really discouraging me.

**Comment by Keqi** [comment]
Hi @Vashiramusa,

Can you send me privately your email address on Slack so I can debug your case?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
