### ISSUE TITLE
I have two absences

### ISSUE THREAD

**Issue by men32z** [microverseinc/microverse-issue-tracker#37]
Hi I have two absences from 2019-08-23 and 2019-08-12, but I've not missed any meetings.

**Comment by Keqi** [comment]
Hi @men32z,

You were present on all meetings according to the system so there is nothing to worry about. However, on 2019-08-23 you seem to have joined as a guest (you weren't signed in to Zoom) and our system couldn't recognize you.

Please, always make sure to sign in to microverse.zoom.us before joining the meeting :)

**Comment by men32z** [comment]
ok, thanks.
