### ISSUE TITLE
I can't see a Join Call button in my dashboard

### ISSUE THREAD

**Issue by Tekcoder** [microverseinc/microverse-issue-tracker#38]
For 
![Screenshot (102)](https://user-images.githubusercontent.com/40640678/64903094-e538cc80-d6aa-11e9-908c-1067e70c2f1f.png)
collaborative learning, I can't find the join call button. Here is the snapshot of my dashboard

**Comment by Keqi** [comment]
Hey @Tekcoder,

What time of the day it was? Video links appear only in the specific time of the day, just before selected block of your daily schedule.

**Comment by Tekcoder** [comment]
Thanks for the clarification
