### ISSUE TITLE
Convert class schedule to respective time zones of cohort.

### ISSUE THREAD

**Issue by yirano** [microverseinc/microverse-issue-tracker#39]

**Comment by Keqi** [comment]
Hi @yirano,

Can you describe the issue in detail? Daily schedules are dynamically set depending on your individual schedule.

**Comment by yirano** [comment]
Currently it shows a schedule based on just UTC-6. I thought it would be more helpful if that schedule was customized to the cohort’s time zone? For example, I am on UTC-4, so instead of it displaying a schedule based on UTC-6, it would be neat if the times were converted to where I am located.

**Comment by Keqi** [comment]
Hey @yirano,

We have no way of knowing where currently you are. We are displaying your dashboard based on the timezone you declared during the on-boarding.

**Comment by yirano** [comment]
Hi morning @Keqi!

I figured you could just pull the location of the user and adjust the time zone from there. Like how you’d locate the user’s location in a weather app? I don’t know how possible that would be but I was having a discussion with a cohort regarding that feature and Ariel suggested I bring it up.

**Comment by yirano** [comment]
Hi morning @Keqi!

I figured you could just pull the location of the user and adjust the time zone from there. Like how you’d locate the user’s location in a weather app? I don’t know how possible that would be as I’m still a cohort, but I thought it would be a neat feature to have.

**Comment by Keqi** [comment]
I think it would be nice to have feature in the future. Thanks for the idea :) We'll discuss it with the team.
