### ISSUE TITLE
Join button not working only for collaborative sections

### ISSUE THREAD

**Issue by vieiramanda11** [microverseinc/microverse-issue-tracker#4]
I'm not able to join the Collaborative Learning with my coding partner. The same window is appearing for both of us: 'Please wait for the host to start this meeting'. I already update everything in my zoom account and follow the procedures suggests by Microverse.

I did not have this issue with my first coding partner and the standup meetings are being registered correctly.

**Comment by Keqi** [comment]
Hi @vieiramanda11,

Have you tried to sign in through https://microverse.zoom.us and grab a link from there? The cause of your issue might be related to different personal links for your private Zoom account and the account created via Microverse Zoom.

Please, let me know if that helps.

**Comment by vieiramanda11** [comment]
Hey @Keqi.
Thank you for your feedback.

So I don't know how to grab a link from there. Can you check and see if my ID in a collaborative meeting is the same? (ID: 237-220-4332) because it's working for standup meetings and coding challenges meetings and was working with my first coding partner as well. 

Thank you again.

**Comment by Keqi** [comment]
Hi @vieiramanda11,

Yes, that is your personal video ID. However, I see that your submitted video link is different in our system: https://us04web.zoom.us/j/2233577036

Can you update it to https://microverse.zoom.us/j/2372204332 and see if that helps?

**Comment by vieiramanda11** [comment]
Hey @Keqi,

I'm sorry for the late answer I just enter in a meeting with my coding partner today. So everything is working now. 

Thank you so much for your help.

Regards,

Amanda.
