### ISSUE TITLE
Fix links to open in a new window on Pathwright

### ISSUE THREAD

**Issue by yirano** [microverseinc/microverse-issue-tracker#40]
Some links open in new windows while others do not.

**Comment by Keqi** [comment]
Hi @yirano,

The rule of thumb is to open internal pages in the same Tab and external links in new tabs. If you find any inconsistency in that, please let us know in this issue :)

**Comment by yirano** [comment]
Oh definitely! I just figured having consistency throughout the entire website would be more helpful.

**Comment by yirano** [comment]
Good morning @Keqi!

I panicked just a little bit reading your comment because I thought I had overlooked that detail so I went ahead and checked to make sure. There are some links on the Onboarding path (Using Github flow to be more specific) where an external link opens in the same Tab. I should have been more descriptive when I opened this comment and I apologize for that.

**Comment by Keqi** [comment]
Hi @yirano

Are you referring to Pathwright? Pathwright is not our own tool so we can't control how links are handled there.

Is there any inconsistency across Student Dashboard that you can see? From what I tested quickly, all links are consistent.

**Comment by yirano** [comment]
@keqi, ah, that’s my mistake!
