### ISSUE TITLE
Dashboard doesn't sync or live reload based on the real time

### ISSUE THREAD

**Issue by wickathou** [microverseinc/microverse-issue-tracker#41]
I found that the dashboard doesn't live reload, so unless I manually reload, I don't see the links to the next meetings or events.

**Comment by Keqi** [comment]
Hello @wickathou,

Are you sure about it? Daily schedule should be refreshing every 30-45 seconds. Can you open /dashboard page and tell me what you see in the Network Tab, is there any activity there?

![image](https://user-images.githubusercontent.com/1449343/65135303-fca6eb00-da05-11e9-8a19-a35a3f897e45.png)

**Comment by wickathou** [comment]
I'll check it out during tomorrow's session

**Comment by wickathou** [comment]
I see that the problem occurs if I don't keep the tab active, which makes sense. I was expecting it to be more like Toggl or Clockify which seem to run offline, as the links to the meetings could stay in the client and the real clock could also be offline. More of a suggestion that a real issue.
