### ISSUE TITLE
Links to repl.it from the challenge progress page and algorithms and data structures on pathwright redirect me to the " algorithms and data structures on pathwright" 

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#42]
https://repl.it/student/submissions/7647735

**Comment by konyan** [comment]
![Screen Shot 2019-09-16 at 10 02 05 PM](https://user-images.githubusercontent.com/6771972/64971410-ab93db80-d8cd-11e9-9b18-40610d4485b2.png)


same like this error @ngodi

**Comment by uzorjchibuzor** [comment]
@ngodi @konyan could you show me where you clicked from?

**Comment by konyan** [comment]
> @ngodi @konyan could you show me where you clicked from?

it is country restriction issues bro, just add proxy addons in browser and easy to fix.

**Comment by ngodi** [comment]
https://repl.it/student/submissions/7848430

**Comment by uzorjchibuzor** [comment]
What I am saying is that I want to see the page that you clicked from? is it from pathwright or from dashboard.microverse.org?

**Comment by ngodi** [comment]
From pathwright and from the dashboard

**Comment by uzorjchibuzor** [comment]
@ngodi apologies for the 21 Questions but could show me a screenshot of the page on the dashboard, and for pathwright.

**Comment by uzorjchibuzor** [comment]
> > @ngodi @konyan could you show me where you clicked from?
> 
> it is country restriction issues bro, just add proxy addons in browser and easy to fix.

Thanks @konyan

**Comment by uzorjchibuzor** [comment]
I am closing this issue. You can reopen it if VPN did not fix it for you.
