### ISSUE TITLE
3 undue absences

### ISSUE THREAD

**Issue by hugopassos** [microverseinc/microverse-issue-tracker#46]
I just noticed now that I'm marked absent in 3 standup meetings:

1 | 2019-09-09 |   |   | ABSENT
2 | 2019-09-06 |   |   | ABSENT
3 | 2019-09-05 |   |   | ABSENT

This is incorrect, I never missed any of the standup meetings or challenge meetings.

**Comment by Keqi** [comment]
Hi @hugopassos,

Can you send me privately your email address on Slack so I can debug your absences?

**Comment by Keqi** [comment]
I reviewed your case @hugopassos,

It seems like you joined meetings as a guest and therefore our system couldn't detect you. It should be happening anymore because we enforced sign-in to Zoom a couple of days ago. I fixed your records.

**Comment by hugopassos** [comment]
Thank you
