### ISSUE TITLE
Not able to join the zoom call

### ISSUE THREAD

**Issue by abruzy** [microverseinc/microverse-issue-tracker#49]
![Screenshot from 2019-09-13 16-22-12](https://user-images.githubusercontent.com/34798898/65054007-c8c7b900-d964-11e9-9a98-93e1081f48ce.png)

**Comment by Keqi** [comment]
Hi @abruzy,

It seems like you have to wait for your coding partner to join the meeting first. I'll look if we can disable this setting and let anyone join the meeting without waiting for a partner.

**Comment by abruzy** [comment]
Alright
