### ISSUE TITLE
Milestone completion not correct

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#5]
Currently working on Final project for rails. We had been accepted to merge until milestone 4 when dashboard was updated. However, milestones 1 to 3 do not show up. We even have a changes required in milestone 1 showing up. 
![Captura de Pantalla 2019-09-06 a la(s) 8 12 09](https://user-images.githubusercontent.com/32690589/64439240-61fdf200-d07e-11e9-97d7-a782b7e112ce.png)

**Comment by nidalaa** [comment]
Hi @misselliev !

Thank you for your report!

As mentioned in the announcement https://microverse.zendesk.com/hc/en-us/articles/360034974513-8-27-2019-Milestones-project-code-review-support:

>„Lex retro non agit.“  This change does not work in backward. If you already completed some milestone project, you will see “Project completed” status only for the first milestone in that project and this is how it should stay for you.

>Please use the Dashboard's milestones forms for the next milestone project.

As before change, you were requesting reviews for milestones as re-reviews of the one `Final project`: everything you submitted there will stay as reviews connected with `Final Project: Milestone 1`. Please submit the completion form for `Final Project: Milestone 1` and ignore status displayed at dashboard for milestones 2 and 3.

**Comment by misselliev** [comment]
Oh okay, that makes a lot of sense. Should I also submit completion forms for M 2 and 3?

**Comment by nidalaa** [comment]
@misselliev feel free to leave it as it is (unless you really want to see "Project Completed" everywhere on your list).
