### ISSUE TITLE
Coding Challenge - Past Due

### ISSUE THREAD

**Issue by Tekcoder** [microverseinc/microverse-issue-tracker#50]
On the first day of commencement of the program, which happens to be Monday, 16, September 2019, the onboarding call was in the place of the morning coding challenge that should take place with my standup team. How do I rectify it on my dashboard? Here you have the screenshot
![Screenshot (103)](https://user-images.githubusercontent.com/40640678/65196281-197c0680-da78-11e9-9cc4-68b3a68d6e6c.png)
:

**Comment by Keqi** [comment]
Hi @Tekcoder,

Indeed, this shouldn't be marked as "Past Due" on the first day. Please ignore it for now and we'll see what we can do about it.
