### ISSUE TITLE
Absence changing dates

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#51]
Hi! I think I mentioned this before but it's happening again.

So for some reason dashboard showed me as absent to stand up on 17/09 yesterday (even when logging in with proper credentials) when I checked, but this morning when I re-checked again the date had changed to 18/09.

**Comment by Keqi** [comment]
@misselliev Thanks for your report. This seems to be a problem with how we deal with student timezones and which day really is today for different people. I'll look into it.

On the other side: Do you still see absences permanently appearing on your dashboard?

**Comment by misselliev** [comment]
I have around 8 absences still appearing including the date-changing one. I'm ignoring them because I have been attending, but I'm checking no new ones show up. I still think it's weird it's only for standups because I join the same way to morning calls too.

Thank you so much for looking into this! It's amazing how fast the responses are.

**Comment by Keqi** [comment]
Hey @misselliev,

I am glad to hear your absences list isn't growing up. We addressed that problem on our side. Please, ignore these past absences. They won't be counted against you. We'll do our best to fix them.
