### ISSUE TITLE
Zoom link on collaborative meetings in the dashboard to my partners meeting room doesn't direct to the right room

### ISSUE THREAD

**Issue by wickathou** [microverseinc/microverse-issue-tracker#52]
The video link from the dashboard seems to redirect to the same address but not the same room. So I seem to be "waiting for host" even though my partner is already in the room waiting.

**Comment by Keqi** [comment]
Hello @wickathou,

Two questions:

- Does it happen only for collaborative sessions or also for coding challenge/standup meetings?
- Does it happen all the time or occasionally?

**Comment by wickathou** [comment]
Hello Keqi,

1) It only for the coding challenge with my partner, for the standups it works fine.

2) 8 out 10 times it hasn't worked

**Comment by Keqi** [comment]
Hi @wickathou,

Is it still a problem for you? We've made some code fixes to prevent that from happening.

**Comment by wickathou** [comment]
Hello Keqi, hasn't happened to me again. Seems to be working fine.
