### ISSUE TITLE
Me and my coding partner join different calls when clicking the "Join Call" button

### ISSUE THREAD

**Issue by hugopassos** [microverseinc/microverse-issue-tracker#54]
Hello,

Right now my coding partner and I can't join the same call by clicking "Join Call". I checked with Willow and we are still coding partners on her side, so apparently there's a bug in our dashboard.

**Comment by Keqi** [comment]
Thanks @hugopassos,

Several students have already reported a similar problem so you're not alone here. We'll look into it :)

**Comment by Keqi** [comment]
This issue has been discussed with @hugopassos on Slack and confirmed as fixed. If it ever happens again, please open a new Github issue.
