### ISSUE TITLE
Absent

### ISSUE THREAD

**Issue by kobiyoyo** [microverseinc/microverse-issue-tracker#55]
am still seeing that am absent which is not true.pls rectify this problem

**Comment by Keqi** [comment]
Hi @kobiyoyo,

Can you please send me your email address privately on Slack so I can debug your issue?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
