### ISSUE TITLE
Completion form - picking reviewers

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#56]
Hi! In submit completion project form, it won't let me pick more than one reviewer.
I'm submitting every reviewer name in the extra field at the bottom of the form instead.

**Comment by Keqi** [comment]
Are you sure about that? It will let you pick multiple reviewers but the select list does not mark then which might be confusing UX. Please, look at the screenshot and try again :)

![image](https://user-images.githubusercontent.com/1449343/65405613-ee2d4a80-dddc-11e9-913d-bc37881a8b4d.png)

**Comment by misselliev** [comment]
Oh okay! Will double check next time I send a completion, thank you!

**Comment by misselliev** [comment]
You're aaaaabsolutely right! Since it won't show up as checkbox or something of that sort, I thought it was a regular dropdown where you can only choose one. Thank you so much for clearing it up!
