### ISSUE TITLE
Submitted a "Challenge completion" form but it's still pending on the dashboard

### ISSUE THREAD

**Issue by jfariasf** [microverseinc/microverse-issue-tracker#57]
Hello,

I submitted the "Challenge completion" for the September 18 but it's still marked as pending. I usually use the buttons on the dashboard but that time I did it through the "Forms" page.

What should I do in this case?

**Comment by Keqi** [comment]
Hi @jfariasf,

Which coding challenge was it? Do you remember?

**Comment by jfariasf** [comment]
Sry for the late answer. I don't remember which one, it's completed on the "progress" page but it was yellow on the dashboard.

**Comment by Keqi** [comment]
Hi @jfariasf,

It seems like two coding challenge forms were submitted for the Sept 17 but none for Sept 18. Do you recall such situation?

I fixed your coding challenge submission manually so it should be marked as submitted on Sept 18.
