### ISSUE TITLE
False absence detected for stand-up meeting

### ISSUE THREAD

**Issue by johnsonsirv** [microverseinc/microverse-issue-tracker#58]
I have tried to resolve the false absence by going over the onboarding process twice, but still no success.
So I am creating the issue here.

**Comment by Keqi** [comment]
Hi @johnsonsirv,

We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
