### ISSUE TITLE
Absent

### ISSUE THREAD

**Issue by abruzy** [microverseinc/microverse-issue-tracker#59]
I attend all my stand up but it shows on my dashboard that I was absent
![Screenshot from 2019-09-25 00-48-01](https://user-images.githubusercontent.com/34798898/65558371-4c1d7780-df2e-11e9-9419-80c0392cbbb2.png)

**Comment by Keqi** [comment]
Hey @abruzy,

Our system shows you were absent during these meetings. Are you sure you joined to correct rooms?

For instance: On September 23 we could see all your team members in the meeting except for you.

**Comment by abruzy** [comment]
I'm sure I join call

**Comment by Keqi** [comment]
Hi @abruzy,

Do you remember if you dropped off the meeting by any reason or had troubles with connection?

**Comment by abruzy** [comment]
I remember now. I was having connection issues

**Comment by Keqi** [comment]
Hi @abruzy,

If you had connection troubles and couldn't join the meeting, you should always request an absence using the form provided on the page. You can also contact Student Success team if this problem happens more often.

Regarding past absences: We won't withdraw them but also they shouldn't be counted against you so nothing to worry about :)
