### ISSUE TITLE
Incorrect absence recorded

### ISSUE THREAD

**Issue by imhta** [microverseinc/microverse-issue-tracker#6]
On the 2019-08-01, the system flagged me as absent yet I was present.

**Comment by Redvanisation** [comment]
I was flagged absent on the 2019-09-06 even though I was present in both meetings.

**Comment by Keqi** [comment]
Hello @imhta,

Thanks for your report. The morning session on 2019-08-01 for your team was indeed incorrectly tracked in our system. I fixed it manually. You shouldn't see an absence anymore.
