### ISSUE TITLE
Absence , 2019-09-18 

### ISSUE THREAD

**Issue by sebastianlujan** [microverseinc/microverse-issue-tracker#60]
Hello, first of all, thank you for solving almost all my absences!
I requested an absence for a dentist appointment and is still being marked as absent
![Screen Shot 2019-09-25 at 12 48 22 AM](https://user-images.githubusercontent.com/1333184/65567873-33ad5d00-df2e-11e9-9582-8bbe46cc163d.png)

**Comment by Keqi** [comment]
Hi @sebastianlujan,

It seems like you requested day off on September 17 but was absent on September 18. Days don't match :)

**Comment by sebastianlujan** [comment]
Yes was my mistake, sorry, it's possible to fix?

**Comment by Keqi** [comment]
Request a day off on the day when you were absent :)

**Comment by Keqi** [comment]
@sebastianlujan I am closing this issue as there is no response for the last 8 days. If you still have some questions or concerns, please re-open it.
