### ISSUE TITLE
i am getting this error "Project You or your partner have already completed Building with Responsive Design" despite me and my partner don't have this project as completed

### ISSUE THREAD

**Issue by yochiwarez** [microverseinc/microverse-issue-tracker#61]
Neither me or my partner have that project completed, i can't request a code review.

**Comment by Keqi** [comment]
Hi @yochiwarez,

Thanks for the report. We'll look into it.

**Comment by yochiwarez** [comment]
I realized that my partner made a mistake by filling the completion form, it is from another project, so that is what is causing the issue, my partner is Juan Pablo Martinez Gil, can you please undone his completion form, for the "Building with Responsive Design" project ??

**Comment by Keqi** [comment]
Hi @yochiwarez,

Can you please ask him to report here about the problem? I am glad to undo his project completion and let you submit a review but I want to hear from you both :)

**Comment by JuanPabloGil** [comment]
Hello @Keqi  I make a mistake uploading the project, I miss click the wrong project  name on the competition form.

**Comment by Keqi** [comment]
Hi @JuanPabloGil, @yochiwarez 

I manually removed this Project Completion from a database. Can you confirm that everything is fine now?

**Comment by JuanPabloGil** [comment]
Everything its working fine !! Thank You!! @Keqi
