### ISSUE TITLE
Project Count on Dashboard

### ISSUE THREAD

**Issue by damiecode** [microverseinc/microverse-issue-tracker#62]
My Dashboard says I have completed 8 projects but I have done only 7.
![Screenshot from 2019-09-25 14-49-42](https://user-images.githubusercontent.com/29799224/65773453-41ccca80-e134-11e9-8823-b9316a530eed.png)
![Screenshot from 2019-09-25 14-49-54](https://user-images.githubusercontent.com/29799224/65773455-42656100-e134-11e9-8e96-100d26fe30e9.png)

**Comment by Keqi** [comment]
Hi @damiecode,

Thanks for your report. This was indeed a small issue in the implementation. Everything should be fine now :)

**Comment by damiecode** [comment]
Hi @Keqi the issue is back again. I am one project ahead on the dashboard.
