### ISSUE TITLE
Wrong absence reported !

### ISSUE THREAD

**Issue by abdellani** [microverseinc/microverse-issue-tracker#63]
Hi 
I got an absence yesterday 26-09-2019.
I acknowledge that this session was different, as after I joined the call, the zoom client crashed after few minutes (2 or 3 ), but I rejoined the call immediately.

Kind regards

**Comment by SofiBretz** [comment]
Hi,
I had the same issue, I got absent from yesterday 26-09-2019.
And I did all the steps and in the punctual time. 
Can you please fix this bug? thanks! :) 

Regards.

**Comment by Keqi** [comment]
Hi @abdellani,

Thanks for your report. Indeed, this meeting was not recorded for some reason but I manually fixed it.

@SofiBretz Please, open a Github issue with your individual case.
