### ISSUE TITLE
Detected absences - Wrong

### ISSUE THREAD

**Issue by vieiramanda11** [microverseinc/microverse-issue-tracker#64]
Hello!

Only today appeared detected absences from 17/09/2019 until yesterday for all of my meetings (coding and standup) and I already did all the steps in the onboarding material.

Regards,

Amanda.

**Comment by Keqi** [comment]
Hi @vieiramanda11,

Your absences have been fixed. This shouldn't be happening anymore. Can you tell me if you were moved to the new team recently?

Thanks!
