### ISSUE TITLE
Wrong absence 09/26/2019 stand-up meeting

### ISSUE THREAD

**Issue by thsvr** [microverseinc/microverse-issue-tracker#65]
Hello Support Team,

I'm having a wrong absence showing in my dashboard related to the ''stand-up meeting'' on 09/26/2019.

Can you please check it?

Thank you in advance :)

Kind regards,

Thaís Vieira

**Comment by Keqi** [comment]
Hello @thsvr ,

Your absence has been fixed. It seems like there was a system disruption in the Zoom because many students were kicked out of their meetings. Did it happen to you too?

**Comment by thsvr** [comment]
Hello Maciej!

No, I didn't have kicked out from the call, everything was normal.

If you have any other questions feel free to ask :)

Have a great day!

Thaís Vieira
