### ISSUE TITLE
Wrong Absence Detected!

### ISSUE THREAD

**Issue by lekegitrepo** [microverseinc/microverse-issue-tracker#66]
Hi,
I discovered this morning that my standup meeting on 2019-09-26 was marked as an absence. I attended the meeting via the join button but I'm confused about how I was marked absent.

**Comment by Keqi** [comment]
Hi @lekegitrepo,

Your absence has been manually fixed. There was a disruption in the Zoom system which caused failure to fetch meetings data. Sorry about that.
