### ISSUE TITLE
Incorrect Absence  2019-09-26

### ISSUE THREAD

**Issue by jucora** [microverseinc/microverse-issue-tracker#68]
Hello guys, in my dashboard an absence appears on 2019-09-26 but it's not correct, I was present.

As I can see, more students are having the same issue, could you please check about it and let me know what happen?

Thank you so much!

Julian

**Comment by Keqi** [comment]
Hi @jucora,

Your absence has been manually fixed. There was a disruption in the Zoom system which caused failure to fetch meetings data. Sorry about that.
