### ISSUE TITLE
Incorrect Absence

### ISSUE THREAD

**Issue by ansaryergesh** [microverseinc/microverse-issue-tracker#69]

**Comment by ansaryergesh** [comment]
Hello Microverse! Just yesterday, there wasn't any absence on the list.  Just now I checked and I had a lot of absences(absences between 17.09.2019- 27.09.2019), but I was present there these days. But before that, there was no absence on the list, and it's weird. 
Can you check it, please! 
Thank you ! 
Ansar

**Comment by Keqi** [comment]
Hi @ansaryergesh,

Thanks for reporting your problem. You absences have been fixed. Can you tell if you were moved between teams recently? This might have been a cause of your issue.

**Comment by ansaryergesh** [comment]
Hello Thank you! Hello Thank you! No, didn't move, stayed at one group from the beginning

**Comment by ansaryergesh** [comment]
But I changed my OS to Linux, maybe for that. Since I had to download Zoom again there. I'm not sure.
