### ISSUE TITLE
Absences issue

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#7]
I have absences for standup meetings where I was present. Could you please help? Thank you so much in advance.

**Comment by Keqi** [comment]
I started checking with the most recent absences you have in your dashboard, 22th, and 23rd of August.

According to the system, standup calls on these days never occurred. Nobody was in the room. Do you happen to remember if your team used another Zoom room (standup or personal link) at that time?

**Comment by Keqi** [comment]
Interesting. Please ignore these absences, they won't be counted against you :) Closing.
