### ISSUE TITLE
Project status stuck on "Changes Required" 

### ISSUE THREAD

**Issue by rmauritsson** [microverseinc/microverse-issue-tracker#73]
We completed the collaborative project **OOP- Milestone 3** with my partner [oscardelalanza](https://github.com/oscardelalanza) and he submitted a project completion form and his dashboard shows "Project Completed" and yet mine is stuck on "Changes required"

**Comment by Keqi** [comment]
Hi @rmauritsson,

Can you please send me your email privately so I can debug your problem?

Thanks!

**Comment by rmauritsson** [comment]
Alright

**Comment by Keqi** [comment]
Hi @rmauritsson,

Have you also submitted a `Project Completion` form? Both of you have to do it :)

**Comment by rmauritsson** [comment]
But how can I submit one when the actions available to me are "Request for
a Code Review" and "View Project".
My partner submitted and he has already even moved onto Rails as I wait for
mine to be sorted out.

**Comment by Keqi** [comment]
You can go to `Forms > Project Completion` and submit the form from there.

**Comment by rmauritsson** [comment]
Oh... Thank You
Wasted a lot of time on that simple thing.

**Comment by Keqi** [comment]
I am glad I could help. Closing this issue.
