### ISSUE TITLE
Electrical Problem and Internet Problem on Detected Absence

### ISSUE THREAD

**Issue by emmanuelkamala** [microverseinc/microverse-issue-tracker#74]
Hi,

On 19th and 20th of September, 2019, my dashboard detected an absence as I missed the last stand up team session, on those two dates, I had an internet bundle issue, on that week, I had to switch to recharging my internet bundle on a daily basis, and it so happened that my bundle got finished like 10 or 15 minutes before the last stand up team session started, so I had to go and get credit so that I activate bundle, but apparently, I got late to get back and join in for the last session.

Also, on the 30th of September, I failed to join in the last stand up team session, as I had an electrical problem at my place, power got cut off for almost like 6 hours, power got back an hour after the last stand up team session, so I could not log in as both my laptop and phone went out of charge. 

The system has detected that I was absent but it's not that I wanted to be absent but circumstances outside my reach, caused such absences.

**Comment by Keqi** [comment]
Hi @emmanuelkamala,

Many students like you have troubles joining meetings due to various unrelated problems and it's okay. You should always request an absence using the form provided on the same page. That way, these absences won't be counted against you.

**Comment by emmanuelkamala** [comment]
The thing is I was not absent, I was there the whole day, from the first stand up to coding with my partner, the issue occurred on my last session, at one time my bundle got finished before my last session, at another time its the electricity that got cut off, but I was not absent.

**Comment by Keqi** [comment]
@emmanuelkamala You should still request absence and explain what was your problem in the `Notes/Comments` section.

**Comment by emmanuelkamala** [comment]
Okay, Noted! Thanks for the clarification
