### ISSUE TITLE
can't submit project for code review

### ISSUE THREAD

**Issue by collinsugwu** [microverseinc/microverse-issue-tracker#75]
The 'request for code review' has been replaced with 'view project', so both me and my partner can't submit our project for review

**Comment by Keqi** [comment]
Hi @collinsugwu,

Thanks for spotting this. We have deployed changes to the Projects Progress page and missed that. It should be fixed now, can you confirm?

**Comment by Keqi** [comment]
This has been fixed in a previous iteration. Closing this issue.
