### ISSUE TITLE
Absences issue

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#76]
Hi! Again with the absences thing still except now they show up in different calls. 
My partner has the same absences (same call, same day) but we were both present on them. 

![Captura de Pantalla 2019-10-02 a la(s) 15 45 17](https://user-images.githubusercontent.com/32690589/66087276-c2703a00-e52b-11e9-8a25-08fb414b4707.png)

**Comment by Keqi** [comment]
Hi @misselliev,

I managed to fix one of these absences but the other one seems like a real problem. I can't see the coding challenge meeting registered on Monday, Sept 30. Do you remember who was on the meeting, which link you used to join? The more details you give me, the higher chance we can track it down :)

**Comment by misselliev** [comment]
Hi @Keqi very sorry about the late response!
I used the same link as dashboard but got some issues logging in with Zoom, when I first started it up it froze so I terminated its task and ran it again, then I could get to login and go into the call.
I think I was the first on call actually. I know my partner came a couple of mins late but that's as far as I remember. Really sorry in advance because it doesn't sound too helpful :(

**Comment by Keqi** [comment]
Hi @misselliev,

There is nothing to worry about. Unfortunately, I can not manually fix your absence because according to the logs, you were absent. However, this won't be counted against your progress in the program :)

Please, request for an absence for this day for a coding challenge meeting.

**Comment by misselliev** [comment]
Hi once again @Keqi ! since this issue is not closed yet, could you please look at yesterday's stand up (2019-10-09) as it shows me absent too?

**Comment by Keqi** [comment]
Hi @misselliev,

I don't see any other absences in your Dashboard. Can you re-check again?

**Comment by misselliev** [comment]
Hey @Keqi you're right, there's none. Weird, it showed up on thursday.

**Comment by Keqi** [comment]
@misselliev Sometimes a Zoom record might not be saved on the first day but it will be synchronized later. Please, let me know if you see more absences in your Dashboard. In the meantime, I am closing this issue.

Thanks!
