### ISSUE TITLE
leetcode challenges

### ISSUE THREAD

**Issue by lilleonz** [microverseinc/microverse-issue-tracker#77]
The Leedtcode challenges on the progress page need to be updated and matched with what is on their page. There is not always a challenge to submit for the challenges on leetcode.

**Comment by Keqi** [comment]
@nidalaa Can you look into it?

**Comment by nidalaa** [comment]
Thanks @lilleonz , we are on it!

**Comment by lilleonz** [comment]
Awesome Thanks!

**Comment by Keqi** [comment]
This has been added to the Curriculum team backlog. Closing.
