### ISSUE TITLE
Problems with the links of the "View Progress" section

### ISSUE THREAD

**Issue by luis-novoa** [microverseinc/microverse-issue-tracker#78]
When I started to study on microverse, clicking on the button "Go to challenge" in the coding challenge section would direct me to the challenge in hackerrank, and clicking on the project name on the projects section would take me to the project's microverse pathway page. Now it is not like that. The project link directs us to the "The Odin Project" page of the project, which is unhelpful since we need to have easy access to the microverse's specific requirements. The "Go to challenge" button now redirects us to this page (https://microverse.pathwright.com/library/fast-track-algorithms-data-structures/69123/path/step/50868450/). Those issues do not make our study impossible, but the website behavior is certainly worse than how it used to be.

**Comment by Keqi** [comment]
It seems like a change made by @nidalaa. Can we have your input here?

**Comment by nidalaa** [comment]
Hi @luis-novoa !

The reason for linking you to the specific step in Pathwright, not to coding challenge platform is that multiple times there are lots of additional resources (videos, explanations, articles) mentioned in Pathwright. As a big number of students started to visit only challenges platforms and skipping reading materials provided  in Pathwright, we decided to make it explicit in Dashboard. More about this change here: https://microverse.zendesk.com/hc/en-us/articles/360035065594-9-30-2019-Coding-challenges-list-in-order

Regarding the links to the specific project - we didn't make any changes to that but to be honest I agree that they should link to Pathwright as well. I will add this to our backlog.

Thanks @luis-novoa !

**Comment by luis-novoa** [comment]
Hi @nidalaa !

Good to know! Regarding the next challenges, it does make sense. I suggest that at least the HackerRank ones take us directly to our challenges since there's no new content on pathwright. Anyway, thank you for your time and consideration.

Best regards,
Luis Novoa

**Comment by Keqi** [comment]
@nidalaa @luis-novoa Thanks you both for figuring it out :) Closing this issue.
