### ISSUE TITLE
Absent for stand up

### ISSUE THREAD

**Issue by collinsugwu** [microverseinc/microverse-issue-tracker#79]
My zoom call redirected me twice to another group, so I canceled it, now I have been recorded absent from stand up meeting.

**Comment by Keqi** [comment]
Hi @collinsugwu,

Can you describe in detail which meetings you were detected as absent and you shouldn't be? It will make it easier for me to debug your case.

**Comment by Keqi** [comment]
Closing as there is no response for two weeks. Please, re-open this issue with more details if the problem is still happening.
