### ISSUE TITLE
Logical Error in My Weekly Progress 

### ISSUE THREAD

**Issue by mohamednaser** [microverseinc/microverse-issue-tracker#80]
Today the first day in week 4 I forgot to submit my retrospective form for the last week so I have to submit it once I submitted the last weel form the weekly goal progress changed to be 10% !! 

this is not logical weekly progress should be dependence on the current week tasks, not old tasks.

find a screenshot for [the issue here ](https://drive.google.com/file/d/1uD1IwvDlQPjNJg2Byzrynax1zC9RaXBT/view?usp=sharing)

**Comment by Keqi** [comment]
Hi @mohamednaser,

It is indeed a bug. Thank you for your report. We'll work on that.

**Comment by Keqi** [comment]
This issue has been fixed and deployed. Closing.
