### ISSUE TITLE
Challenge completion link broken

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#81]
When on the Algorithms and Data Structures curriculum you want to click on the challenge completion link that sends you to the form in the dashboard, it takes you to the older airtable form that has been deactivated instead of the current form for submitting the coding challenge. ;) 
This issue happens on the repl.it coding challenges.

**Comment by Keqi** [comment]
Hi @majovainilla,

Thanks for noticing it. I have updated all links in the Algorithms and Data Structures section.
