### ISSUE TITLE
another false absence for 2nd october 2019. 

### ISSUE THREAD

**Issue by johnsonsirv** [microverseinc/microverse-issue-tracker#82]
I have not missed any attendance, especially evening standups, because I enjoy it alot with my team.

**Comment by johnsonsirv** [comment]
2nd October was a day after the Local Holiday for My countries Independence (1st October), and I didn't request an absence
I joined the meeting on 1st of October, and also on the 2nd and till date. Kindly review

**Comment by Keqi** [comment]
Hi @johnsonsirv,

According to the system logs you were absent on a StandUp meeting on October 2. Can you describe more circumstances of how you joined the meeting? Perhaps, you had some connection problems or Zoom was kicking you out of the meeting?

**Comment by johnsonsirv** [comment]
Hi @Keqi,
Thanks for your response.

I joined the meeting on 2nd October. The first time it connected, and I joined successfully. After some time I had network fluctuation, I was logged off. After several attempts, I then joined back the meeting successfully, and that was it. Till the end of the meeting, before I left.

**Comment by Keqi** [comment]
Hi @johnsonsirv,

It seems like your connection problems might have marked you as absent but please don't be worried about this. I can't modify this database record but you also won't be counted as absent because you explained your case.

Please, ignore this absence and carry on :)
