### ISSUE TITLE
Marked as absent while all of my team asked for absence.

### ISSUE THREAD

**Issue by othman-19** [microverseinc/microverse-issue-tracker#84]
Hi,
    That was Friday 27-09-2019 ,in stand up meeting, all my stand up team asked for official absence request from microverse, I was alone in that stand up meeting, after that I have got marked as absent.

**Comment by Keqi** [comment]
Hi @othman-19,

This is an exceptional situation that we're trying to solve programmatically. Can you please consult it with the Student Success team and ask them how to solve this issue?

**Comment by Keqi** [comment]
Hi @othman-19,

The Student Success team should have already reached out to you. I am closing this issue.
