### ISSUE TITLE
logical error in progress calculations 

### ISSUE THREAD

**Issue by mohamednaser** [microverseinc/microverse-issue-tracker#85]
am in week number 4 and I should solve 19 code challenges and it's done correctly but I don't know why in 07, 09 system makes it as post due and I should submit this challenges and it's already submitted and if I want to resubmit the form it refused because it's a duplicate for the same code challenge . 

kindly find the attachments here : 

- [attachment 1 ](https://drive.google.com/open?id=1uibiTegs5ZGsdUz-sYUAsszjr3J9VpDc)
- [attachment 2 ](https://drive.google.com/open?id=1Pci0HPg2d9I0nwGgTOXFtYllNEcl_r-_)
- [attachment 3 ](https://drive.google.com/file/d/16lsRQtnZZBnPCe7PAwyBQrQxgpvmoSkx/view?usp=sharing)

**Comment by Keqi** [comment]
The calendar only checks if you submitted a coding challenge today. If not, it will be marked as "Past Due". The specific coding challenge is not related to the day. It can be submitted on any day you finished it. The same coding challenge can not be submitted twice.

Can you please elaborate please where you see a logical error in the calendar? :)

**Comment by mohamednaser** [comment]
current calendar behavior now  if you forget to submit the code challenge form and standup meeting form and try to fill these forms at any day 

1- code challenge button will be on the same status "Past Due "
2- standup button will changes to green with a submitted label as normal 

my question is this is normal behavior to change standup button status and not change the code challenge status?

**Comment by mohamednaser** [comment]
I got it thanks
