### ISSUE TITLE
repl.it  Not found error

### ISSUE THREAD

**Issue by IBUNHABIBU** [microverseinc/microverse-issue-tracker#87]
Error loading: You are not authorized to perform this operation.

![Repl](https://user-images.githubusercontent.com/14271563/66737791-929f2b80-ee75-11e9-9432-5643a0f09a49.PNG)

 _Help I can't access coding challenges_

**Comment by nidalaa** [comment]
Hi @IBUNHABIBU !

Could you tell me which coding challenge you tried to access (pathwright link will be enough)? 

Also, can you check if you can open:

- [ ] https://repl.it/student_embed/assignment/2667685/acf72407e8a5c461eda3fd5fe956a461
- [ ] https://repl.it/student/classrooms/117833

**Comment by IBUNHABIBU** [comment]
The links you have given me they are working but  the link from  Trees and
Graphs: Is it a Search Tree? and so on  are not working

Tarehe Jumanne, Okt 15, 2019 saa 18:27 Emilia Andrzejewska <
notifications@github.com> aliandika:

**Comment by gootyfer** [comment]
Hi @IBUNHABIBU ! Sorry for the late reply. Thanks for reaching out to us.
I have just updated the links to "Is it a Search Tree?" and "Is is balanced?" of the "Trees and Graphs" section. Please, tell me if you can already use them correctly and if you had issues with any other link to a replit challenge.
Thanks a lot!

![super](https://user-images.githubusercontent.com/759396/68470623-b8bdae80-021c-11ea-996d-4ca7e3bde912.gif)

**Comment by IBUNHABIBU** [comment]
Thanks , now it works

Tarehe Ijumaa, 8 Nov 2019 saa 13:41 Israel Gutiérrez <
notifications@github.com> aliandika:
