### ISSUE TITLE
Wrongfully marked as Absent

### ISSUE THREAD

**Issue by paulgureghian** [microverseinc/microverse-issue-tracker#89]
The 'Join Call' button was not on my Dashboard. 
![Capture9](https://user-images.githubusercontent.com/8146561/66952731-09712b80-f012-11e9-94a3-679d7a54f820.PNG)

**Comment by Keqi** [comment]
Hi @paulgureghian,

It's very interesting. Can you remember of any unusual circumstances around that time? Perhaps, you were moved to the other team?

You can also bookmark the standup call link in your browser if it doesn't appear on the Dashboard.

**Comment by Keqi** [comment]
Closing as there is no response for 8 days. Please re-open this issue if you want to continue the discussion about absences :)
