### ISSUE TITLE
coding challenge is not changing to "submitted" when I submit it, while on "past due"

### ISSUE THREAD

**Issue by shadymedy** [microverseinc/microverse-issue-tracker#9]
My coding challenge is not changing to "submitted" when I submit it while on "past due".
I later realize that It had changed on the challenges_progress section but is not changing on the dashboard section

**Comment by Keqi** [comment]
@shadymedy Can you please tell me which coding challenge and day in the calendar are you referring to? It will help me debug this problem.

**Comment by Keqi** [comment]
Closing due to two reasons:

- This may be a broader issue when people are submitting Friday's assignments, we're investigating it.
- No response in this issue for 19 days.
