### ISSUE TITLE
Broken link in Curriculum

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#90]
Hi!

Just to let you know that the link to see the alumni profiles on LinkedIn is broken! 

Pathwright section:
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54656843/

Broken link: "other Microverse students"
https://www.linkedin.com/school/microverseinc/alumni/

Thanks!

**Comment by Keqi** [comment]
Hi @majovainilla,

Thanks for your precise eye. We really appreciate it. It has been fixed :)
