### ISSUE TITLE
Error in the tests for repl.it coding challenge called 7.3. Insertion Sort Itself

### ISSUE THREAD

**Issue by davidauza-engineer** [microverseinc/microverse-issue-tracker#91]
Hi, I would like to report a weird behavior I'm having by solving the repl.it challenge called 7.3. Insertion Sort Itself. When I try to submit looks like it passes the test cases but it displays a failed message. When I try to click What's wrong nothing is displayed.

Below you can find some screenshots:

![Screenshot 1](https://p19.zdusercontent.com/attachment/9304358/nrPS4M7okFrPg2vMPck3W1c6g?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..TKzUqAVFS1rgicejukiuBg.wMuTPj8PXVhmPqmXNBI5TPV2cFjjrt4tBsujRJZPgmvd4_xjE4710XMQVIxuvBo5K1j7vW-wYuetB0gsE1R0NlXtb7AQyuZZFL0VOiz9KfwJ8D82F6hwMPKz-1nRwVsjc1ZycExzVAnk_2VMi3-AcOO9fD7wWjPe5J97_Gq_kTdNxsMGV5oWeIIofiFuV0hPD62rf88vJXF7fcnLZZa5Qp9AQAanTlXh0n_Ejh3z7Z2qERvJ_ux_89NtSGP3I5QMPtRdzxD7HAN_RAhE2H-zpQ50VHBzAKk8G-7JvpzWq8k.rIBtnrhLW-oq2_xj5uB-sg)

![Screenshot 2](https://p19.zdusercontent.com/attachment/9304358/vHR10yBje2qnddMKi28ZGVa52?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..prIVFj2QAHzTcB9Auz2zew.l71cQSjZugzhEuZ1fogW8HEAIDprliOS9xxCPuT-Pb27xWrljneeLDInlw2TER_nH54-Rbumlo6WN-dg-aRy3iv22i5pbGpFmgF7SVJBXibJnUG65_6NIK98ir6lBX6EcSrhtVdn50WVuCw1_eGiJ4km-wBndsyjwhN0fOp8KVxWEw78sFaL21k_UYqfYMaNEUuh2W_FL0F_e1yFqhCm6cuAda1xmxNs-F_r_qLGWB3Fgg_Zt0xt0LwCy9w3K_Rub7l3c6tLHSkwsUwKYX_kCTnM9ElfPsMcUl6cnlLkW-k.YRfp76CH_RDlPi4wdkwgOg)

Thanks, please let me know if you need further information :)

**Comment by Keqi** [comment]
Hi @davidauza-engineer,

I wish I could help you with this error but Repl.it page is not in our control. Can you report it to them and let us know about the result? https://repl.it/site/about

**Comment by davidauza-engineer** [comment]
@Keqi Sure, I'll do it and I'll let you know about their answer :)

**Comment by davidauza-engineer** [comment]
@Keqi I changed my algorithm and everything is working now. I think the problem was related to my algorithm not doing the right job. However, I did report everything to repl.it so they can handle the situation and hopefully show appropriate error messages for the future students

**Comment by Keqi** [comment]
Thanks, @davidauza-engineer. I am glad to hear you solved the problem. Closing this issue :)
