### ISSUE TITLE
invalid absence recorded for 17/10/2019 standup

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#92]
Hi Team, please double check because I attended the meeting till the end. Thanks

**Comment by Keqi** [comment]
Hi @ngodi,

I am afraid there is no absence on 17/10 but I can see there was no meeting on Friday 18/10 according to the logs. Can you confirm it?

**Comment by Keqi** [comment]
It's very weird. Our system does not see you on Oct 18. Anyways, don't worry about it too much, you don't have too many absences recorded so it shouldn't count against you.
