### ISSUE TITLE
Regarding false absent recorded

### ISSUE THREAD

**Issue by sumancrest0001** [microverseinc/microverse-issue-tracker#95]
I had requested for the absence but my last 2 stand up requests are marked as absent. I think the issue was due to the timezone difference. I would appreciate if you fix this problem.

**Comment by Keqi** [comment]
Hi @sumancrest0001,

Can you send me your email OR name and surname so I can debug your issue?

Thanks!

**Comment by sumancrest0001** [comment]
Hello Maciej,
My name: Suman Shrestha
Email address: suman.crest0001@gmail.com

**Comment by Keqi** [comment]
Hey @sumancrest0001,

I can see you requested an absence on Oct 16 but you were absent on Oct 15. Would you like to submit a retroactive form for Oct 15?

**Comment by Keqi** [comment]
Closing as there is no response for 2 weeks.
