### ISSUE TITLE
First Day 

### ISSUE THREAD

**Issue by Datagirlcmr** [microverseinc/microverse-issue-tracker#97]
I can't find the "Join Call Button" as specified on the onboarding Materials. I followed the instructions carefully
![join](https://user-images.githubusercontent.com/49751568/67223660-eae1aa80-f3ec-11e9-8e8d-2ba82985e98f.PNG)

**Comment by Keqi** [comment]
Hi @Datagirlcmr,

Everything should be okay now. Can you re-check?
