### ISSUE TITLE
zoom call

### ISSUE THREAD

**Issue by Tresor11** [microverseinc/microverse-issue-tracker#98]
I'm having issues joining the zoom call with my partner and my team

**Comment by didymus707** [comment]
The same here, I couldn't join the meeting last night and the same is happening this morning again. The join call notification is not popping up on my dashyboard

**Comment by Keqi** [comment]
@Tresor11 @didymus707 Is this still a problem for you? We have synced your Zoom accounts so everything should be fine now :)

**Comment by didymus707** [comment]
No, thanks
