### ISSUE TITLE
Let me fix the Dashboard Request an Absence button

### ISSUE THREAD

**Issue by Khairul3232** [microverseinc/microverse-issue-tracker#99]
Hi, 

I cannot request for absence through the dashboard. The button does not work. 

I can offer to help you fix the bug on the dashboard if you like. 

Regards, 
K.

**Comment by digomes87** [comment]
Hi I don't know why but my absence isn't tracker.
Willow told me that I have a month miss, but I don't miss no day.

I use the same email in clockyfy and Microverse, that is diego.gomes87@gmail.com

Tks

**Comment by Keqi** [comment]
Hi @Khairul3232,

Do you mean the button here? https://dashboard.microverse.org/absences `Request an Absence`. It should take you to the Airtable.

@digomes87 Can you please create a separate issue describing your problem?

**Comment by Keqi** [comment]
Hi @Skyrul,

This button works for me. It takes you to Absences form in Airtable. How does it work for you?

**Comment by Keqi** [comment]
Closing as there is no response for 2 weeks. Please re-open the issue if you need to continue a discussion.
